V3.5.x add api for pufa
Tencent/bk-cmdb pull request #4592
Opened 2020-08-31 03:44 UTC by Dravening

### 新加的功能:
- 新增查询实例所有关联接口（依照bk_obj_id和bk_inst_id确认实例，找出所有关联）
- 新增删除实例所有关联接口（依照bk_obj_id和bk_inst_id确认实例，删除所有关联）

2020-09-03 13:36 UTC, breezelxp requested changes

2020-09-03 13:36 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +		request.Limit.Limit = 500
这个地方要报错，不能给默认值

2020-09-03 13:36 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association.go
> +	//}
删除了

2020-09-04 01:55 UTC, Dravening commented on src/scene_server/topo_server/core/operation/association.go
> +	//}
已删除

2020-09-04 01:55 UTC, Dravening commented on src/scene_server/topo_server/service/association.go
> +		request.Limit.Limit = 500
已修正

2020-09-04 06:57 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +	}
这地方有性能问题

2020-09-04 06:57 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +	queryResult := &metadata.QueryResult{}
用new

2020-09-04 06:57 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association.go
> +		Condition: request.Condition,
参数要做校验

2020-09-04 13:55 UTC, breezelxp approved these changes

2020-09-04 13:57 UTC, merged