操作审计重构. issue #4601
Tencent/bk-cmdb pull request #4602
Opened 2020-09-01 13:39 UTC by LieLieLiekey

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2020-09-03 13:23 UTC, wcy00000000000000 requested changes

2020-09-03 13:23 UTC, wcy00000000000000 commented on src/common/auditlog/instance.go
> +}
空行

2020-09-03 13:23 UTC, wcy00000000000000 commented on src/scene_server/datacollection/collections/hostsnap/hostsnap.go
> +	"configcenter/src/common/http/rest"
位置

2020-09-03 13:23 UTC, wcy00000000000000 commented on src/scene_server/datacollection/collections/middleware/handler.go
> +	"configcenter/src/common/auditlog"
位置

2020-09-03 13:23 UTC, wcy00000000000000 commented on src/common/auditlog/hostsnap.go
> +	input := &metadata.HostModuleRelationRequest{HostIDArr: []int64{hostID}, Fields: []string{common.BKAppIDField}}
主机的业务ID不需要每次都查，有的是之前就知道的

2020-09-04 05:46 UTC, LieLieLiekey commented on src/common/auditlog/hostsnap.go
> +package auditlog
后面改了。这个是draft，包导入顺序和注释不一定准时更新

2020-09-07 02:56 UTC, wcy00000000000000 commented on src/common/auditlog/hostmodule.go
> +}
生成审计数据的部分也要放在这里

2020-09-07 02:56 UTC, wcy00000000000000 commented on src/common/auditlog/host.go
> +func (h *hostAuditLog) GenerateAuditLog(kit *rest.Kit, action metadata.ActionType, hostID, bizID int64, innerIP string,
建议参考实例审计做成批量的

2020-09-07 06:12 UTC, LieLieLiekey commented on src/common/auditlog/hostmodule.go
> +}
1

2020-09-07 07:48 UTC, closed without merging