升级redis driver并对其进行封装
Tencent/bk-cmdb pull request #4691
Opened 2020-09-23 03:45 UTC by fireyun

### 新加的功能:
- 升级redis driver为go-redis
- 对go-redis进行一层封装，提升代码的可扩展性和可维护性
- 支持sentinel加密配置

close issue #4688

2020-09-24 09:24 UTC, breezelxp commented on src/scene_server/datacollection/service/service.go
> +	netCli  redis.Client
这个是指针类型的吗？

2020-09-24 09:59 UTC, fireyun commented on src/scene_server/datacollection/service/service.go
> +	netCli  redis.Client
interface类型

2020-10-09 06:21 UTC, rentiansheng commented on scripts/init.py
> +        redis_pass_v, sentinel_pass_v, mongo_ip_v, mongo_port_v, mongo_user_v, mongo_pass_v, rs_name, user_info,
paas 这个命名容易误解， 建议改为pwd

2020-10-09 06:26 UTC, rentiansheng requested changes

2020-10-09 06:26 UTC, rentiansheng commented on src/apiserver/service/filter.go
> +		result, err := s.cache.Eval(context.Background(), setRequestCntTTLScript, []string{key}, rule.TTL).Result()
这个ctx 可以不再这里生成吗？让上层还输传递过来

2020-10-09 06:27 UTC, rentiansheng commented
如果能将redis 使用从struct字段传递改为直接使用driver 就更好了

2020-10-19 06:44 UTC, breezelxp approved these changes

2020-10-19 06:45 UTC, merged