feature: execute migrate specify version issue #4757
Tencent/bk-cmdb pull request #4758
Opened 2020-10-15 09:28 UTC by rentiansheng

### 新加的功能:
- 指定执行的migrate版本
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2020-10-15 09:48 UTC, wcy00000000000000 requested changes

2020-10-15 09:48 UTC, wcy00000000000000 commented on src/scene_server/admin_server/service/migrate.go
> +	ownerID := common.BKDefaultOwnerID
这里给ownerID赋了默认值，URL里的这个参数就没有用了

2020-10-15 09:52 UTC, wcy00000000000000 commented on src/scene_server/admin_server/service/migrate.go
> +	fmt.Println(time.Now().Unix(), subTS)
这个是否需要删除？

2020-10-20 08:09 UTC, breezelxp approved these changes

2020-10-20 08:11 UTC, breezelxp approved these changes

2020-10-20 08:11 UTC, merged