主机更新创建时对bk_cloud_id做校验，必须为数值型
Tencent/bk-cmdb pull request #4763
Opened 2020-10-19 02:22 UTC by fireyun

### 优化的功能:
- 主机更新创建时对bk_cloud_id做校验，必须为数值型

2020-10-19 02:39 UTC, breezelxp requested changes

2020-10-19 02:39 UTC, breezelxp commented on src/source_controller/coreservice/core/instances/instance_validate.go
> +				blog.Errorf("invalid bk_cloud_id value:%#v, err:%v", BKInnerObjIDHost[common.BKCloudIDField], err)
rid带上

2020-10-19 02:39 UTC, breezelxp commented on src/scene_server/host_server/service/host.go
> +	}
这个返回合适？

2020-10-19 06:19 UTC, fireyun commented on src/source_controller/coreservice/core/instances/instance_validate.go
> +				blog.Errorf("invalid bk_cloud_id value:%#v, err:%v", BKInnerObjIDHost[common.BKCloudIDField], err)
已加

2020-10-20 08:03 UTC, breezelxp approved these changes

2020-10-20 08:04 UTC, merged