修复时间类型错误
Tencent/bk-cmdb pull request #4765
Opened 2020-10-19 02:23 UTC by ZQHcode

### 修复的问题：
- 时间类型校验错误 close issue #4731

2020-10-19 02:37 UTC, rentiansheng requested changes

2020-10-19 02:37 UTC, rentiansheng commented on src/scene_server/admin_server/upgrader/y3.9.202010151148/update_inst_time_val.go
> +	for _, objID := range objIDArray {
模型是用户可以新加的。 你需要通过cc_ObjDes 拿到所有的模型， 或者是通过实例表（cc_ObjectBase）拿到所有的模型也行

2020-10-19 02:37 UTC, rentiansheng commented on src/scene_server/admin_server/upgrader/y3.9.202010151148/update_inst_time_val.go
> +		dbc := mongo.GetDBClient()
为什么不用db呀？

2020-10-19 02:37 UTC, rentiansheng commented on src/scene_server/admin_server/upgrader/y3.9.202010151148/update_inst_time_val.go
> +		mongo, ok := db.(*local.Mongo)
加这个做什么？

2020-10-19 02:37 UTC, rentiansheng commented on src/scene_server/admin_server/upgrader/y3.9.202010151148/update_inst_time_val.go
> +			if err := cursor.All(ctx, &insts); err != nil {
dal 中写好了Find().All 这里为什么不使用呀？

2020-10-19 02:37 UTC, rentiansheng commented on src/scene_server/admin_server/upgrader/y3.9.202010151148/update_inst_time_val.go
> +								doc[field] = util.Str2Time(valStr)
这里是会有失败的可能， 一个转换是不是写的太复杂了


这里简化下吧

2020-10-19 02:37 UTC, rentiansheng commented on src/source_controller/coreservice/core/instances/instance_validate.go
> +func (m *instanceManager) changeStringToTime(ctx context.Context, valData mapstr.MapStr, propertys []metadata.Attribute) {
context 改为kit *rest.Kit,

2020-10-27 03:12 UTC, rentiansheng submitted a review, later dismissed
同过

2020-11-02 15:16 UTC, breezelxp approved these changes
LGTM

2020-11-02 15:16 UTC, merged