refactor: 修改批量删除关联实例的实现逻辑，并为其增加审计功能。
Tencent/bk-cmdb pull request #4791
Opened 2020-10-22 11:48 UTC by Dravening

### 优化的功能:
- 修改批量删除关联实例的实现逻辑，并为其增加审计功能。

close #4743

2020-10-23 07:13 UTC, rentiansheng requested changes

2020-10-23 07:13 UTC, rentiansheng commented on src/apimachinery/coreservice/association/api.go
> -func (asst *association) DeleteInstAssociationBatch(ctx context.Context, h http.Header, input *metadata.DeleteOption) (resp *metadata.DeletedOptionResult, err error) {
这个为什么删掉了

2020-10-23 07:13 UTC, rentiansheng commented on src/scene_server/topo_server/core/operation/association.go
> +			blog.Errorf("DeleteInst failed, get instance association failed, params: %+v, err: %+v, rid: %s", params, err, params.ReqID)
这里不需要返回错误， 日志里面又复杂结构， 建议使用blog.ErrorJSON, 下同

2020-10-23 07:13 UTC, rentiansheng commented on src/source_controller/coreservice/service/association.go
> -func (s *coreService) DeleteInstanceAssociationBatch(ctx core.ContextParams, pathParams, queryParams ParamsGetter, data mapstr.MapStr) (interface{}, error) {
为什么删除， 修改也应该需要又新加的sdk

2020-10-23 07:45 UTC, Dravening commented on src/scene_server/topo_server/core/operation/association.go
> +			blog.Errorf("DeleteInst failed, get instance association failed, params: %+v, err: %+v, rid: %s", params, err, params.ReqID)
已修正。

2020-10-23 08:56 UTC, rentiansheng commented on src/scene_server/topo_server/core/operation/association.go
> +			break
这里的错误是不是没有处理

2020-10-26 06:33 UTC, rentiansheng requested changes

2020-10-26 06:33 UTC, rentiansheng commented on src/scene_server/topo_server/service/association.go
> +			return nil, err
这个地方应该是返回一个ccError， 看下这个错误吗？ 	common.CCErrCommHTTPDoRequestFailed

2020-10-26 06:33 UTC, rentiansheng commented on src/scene_server/topo_server/service/association.go
> +		} else if ret.Code != 0 {
这个地方应该判断ret.Result 或者直接使用ret.CCError()

eg

if err := ret.CCError(); err != nil {
........
}

2020-10-26 06:37 UTC, Dravening commented on src/scene_server/topo_server/service/association.go
> +		} else if ret.Code != 0 {
已修正

2020-10-26 07:49 UTC, rentiansheng approved these changes
通过

2020-10-26 07:49 UTC, merged