fix: 修正excel导出的关联关系表格中没包含此实例作为“关联目标模型”关联关系的错误。
Tencent/bk-cmdb pull request #4824
Opened 2020-11-03 03:24 UTC by Dravening

### 修复的问题：
- fix: 修正excel导出的关联关系表格中没包含此实例作为“关联目标模型”关联关系的错误。

此处用了很多mapstr结构，很难理清逻辑，下面简要说明：
1.在getAssociationData函数中，增加关联关系目标模型的位置；
2.使后续lgc.fetchInstAssocationData函数得以查询到相关信息；
3.最后修正BuildAssociationExcelFromData函数中不正确的写入逻辑。

2020-11-03 03:34 UTC, Dravening commented
close #4823

2020-11-11 10:11 UTC, breezelxp requested changes

2020-11-11 10:11 UTC, breezelxp commented on src/web_server/logics/association.go
> +	result := append(bkObjRst.Data[:], bkAsstObjRst.Data...)
bkObjRst.Data[:]，这个不用这么写，直接写(bkObjRst.Data就可以

2020-11-16 09:24 UTC, closed without merging

2020-12-04 06:20 UTC, Dravening commented
这个已经在其它的pr里面合进去了