feature: 增加更新服务实例的接口 issue #4830
Tencent/bk-cmdb pull request #4831
Opened 2020-11-04 14:02 UTC by fireyun

### 新加的功能:
- 增加更新服务实例的接口

close issue #4830

2020-11-09 08:49 UTC, breezelxp requested changes

2020-11-09 08:49 UTC, breezelxp commented on src/source_controller/coreservice/core/process/service_instance.go
> +		}
这个应该是在validate里去做，而且限制只能更新这个字段。

2020-11-09 09:55 UTC, fireyun commented on src/source_controller/coreservice/core/process/service_instance.go
> +		}
嗯，可以在场景层的validate加上校验，这里的检查主要是为了不带入多余的无用字段

2020-11-10 08:33 UTC, breezelxp approved these changes

2020-11-10 08:33 UTC, merged