feature: 在主机的导出excel中增加"业务"栏,并更改相关cell外观。
Tencent/bk-cmdb pull request #4844
Opened 2020-11-06 09:28 UTC by Dravening

### 优化的功能:
- 在主机的导出excel中增加"业务"栏,并更改相关cell外观。

close #4843

2020-11-09 07:29 UTC, rentiansheng commented on src/web_server/logics/util.go
> +			PropertyType:  common.FieldTypeBizTopo,
这个是不需要的。 这里表示的是数据类型，

2020-11-09 07:42 UTC, rentiansheng requested changes

2020-11-09 07:42 UTC, rentiansheng commented on src/web_server/logics/excel_util.go
>  	// 给第一列剩下的空格设置颜色
将这个循环删了， 改成		sheet.Col(0).SetStyle(colStyle)  来设置第一列的样式

2020-11-09 07:42 UTC, rentiansheng commented on src/web_server/logics/excel_util.go
> +			for i := 3; i < 1000; i++ {
每一行值内容需要摄者颜色吗？

2020-11-09 07:42 UTC, rentiansheng commented on src/web_server/logics/excel_util.go
> +			cellType.Value = "--"
修改 354行：在这里设置 字段ID,字段类型的值
```
	        cellType := sheet.Cell(1, index)
		cellType.Value = fieldTypeName			cellType.Value = fieldTypeName
		cellType.SetStyle(styleCell)			cellType.SetStyle(styleCell)
```

2020-11-09 08:50 UTC, Dravening commented on src/web_server/logics/excel_util.go
> +			for i := 3; i < 1000; i++ {
体现值内容不可修改，如果没有颜色，看起来像是可以修改的

2020-11-09 09:03 UTC, Dravening commented on src/web_server/logics/util.go
> +			PropertyType:  common.FieldTypeBizTopo,
啊。。这里我在后边加了逻辑，看这里
https://github.com/Tencent/bk-cmdb/blob/6276187c98b5ff49e1a07bee24ddc9df605542a6/src/web_server/logics/excel_util.go#L389

2020-11-09 09:04 UTC, rentiansheng commented on src/web_server/logics/util.go
> +			PropertyType:  common.FieldTypeBizTopo,
这个逻辑是不需要的。 为什么一定要用type 判断， 这个type不是做这个用的

2020-11-09 09:11 UTC, Dravening commented on src/web_server/logics/excel_util.go
>  	// 给第一列剩下的空格设置颜色
ok

2020-11-09 09:20 UTC, Dravening commented on src/web_server/logics/excel_util.go
> +			cellType.Value = "--"
这里没太明白。
这里保留353行的原因是为了其它列能正常填入值。
在389行之后的代码会重设一次“业务拓扑”的表格格式，不会占用太多资源的。

2020-11-09 11:01 UTC, Dravening commented on src/web_server/logics/excel_util.go
>  	// 给第一列剩下的空格设置颜色
不行，我刚测试了。这样改会丢失空白格的颜色。
 sheet.Col(0).SetStyle(colStyle) 的方式仅在格子有内容的情况下才生效。

2020-11-09 11:48 UTC, Dravening commented on src/web_server/logics/util.go
> +			PropertyType:  common.FieldTypeBizTopo,
主要是，我没有想出好的办法能实现“业务”和“业务拓扑”两列变色。
目前有三种方案：1.使用type判断  2.改结构体，新加个结构属性做判断  3.使用name判断，但是name的内容是国际化之后的内容，并不好。

如果序号1方案不行的话，我拟定采用序号2方案。

2020-11-09 13:43 UTC, Dravening commented on src/web_server/logics/util.go
> +			PropertyType:  common.FieldTypeBizTopo,
已修正

2020-11-10 06:58 UTC, rentiansheng commented on src/web_server/logics/excel_util.go
> +	for i := 3; i < 1000; i++ {
这个值不合理，建议看下 excel xls 格式最大值是多少

2020-11-10 07:00 UTC, rentiansheng commented on src/web_server/logics/excel_util.go
> +		"business topology": 1,
这里key可以 使用language 取当前语言对应的值。 不需要所有的语言都写到这里， 这样没法支持更多的国际化的

2020-11-10 07:03 UTC, Dravening commented on src/web_server/logics/excel_util.go
> +		"business topology": 1,
啊，是的，i was stupid.

2020-11-10 07:54 UTC, Dravening commented on src/web_server/logics/excel_util.go
> +	for i := 3; i < 1000; i++ {
已解决

2020-11-10 10:53 UTC, Dravening commented on src/web_server/logics/excel_util.go
> +		"business topology": 1,
已解决

2020-11-12 02:50 UTC, rentiansheng commented on src/web_server/logics/excel_util.go
> +		common.ExcelFirstColumnInstData}
这个换下行， 保持一致

2020-11-12 13:11 UTC, rentiansheng requested changes

2020-11-16 09:09 UTC, rentiansheng approved these changes
通过

2020-11-16 11:51 UTC, breezelxp approved these changes

2020-11-16 11:51 UTC, merged