运营统计优化
Tencent/bk-cmdb pull request #4845
Opened 2020-11-06 11:01 UTC by tiger-guo

### 新加的功能:
- xxxx
### 优化的功能:
- 运营统计优化
### 修复的问题：
- xxxx

2020-11-09 08:21 UTC, breezelxp requested changes

2020-11-09 08:21 UTC, breezelxp commented on src/source_controller/coreservice/core/operation/inner_chart.go
> +	AuditLog_ResourceID_Field               = "resource_id"
变量遵行驼峰原则，局部变量小驼峰，需要导出的大驼峰。

2020-11-09 08:21 UTC, breezelxp commented on src/source_controller/coreservice/core/operation/inner_chart.go
> +	} else {
这个else是不是可以不要？

2020-11-09 08:21 UTC, breezelxp commented on src/source_controller/coreservice/core/operation/inner_chart.go
> +	if err := mongodb.Client().Table(common.BKTableNameAuditLog).Find(createCond).Fields(fields...).All(kit.Ctx, &createAuditLogs); err != nil {
这些不是要分页么?

2020-11-09 08:29 UTC, tiger-guo commented on src/source_controller/coreservice/core/operation/inner_chart.go
> +	} else {
不可以啊 如果今天不存在数据，那需要插入数据，之前的逻辑没有else，每次都进行这一步操作，其实是多余的，如果存在更新就好了，不需要插入

2020-11-11 09:28 UTC, breezelxp approved these changes

2020-11-11 09:28 UTC, merged