feature: discovery services on demand issue #4675
Tencent/bk-cmdb pull request #4881
Opened 2020-11-22 07:16 UTC by rentiansheng

### 新加的功能:
- 按需动态发现依赖的服务
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2020-11-23 12:15 UTC, wcy00000000000000 requested changes

2020-11-23 12:15 UTC, wcy00000000000000 commented on src/scene_server/admin_server/app/discovery.go
> +	// 不依cc其他组件，只发自己即可, 默认会自动加上发现发下相同的服务。这里是为了避免为空的时候发现全部服务
错别字：不 _依_ cc其他组件，只 _发_ 自己即可, 默认会自动加上发现 _发下_ 相同的服务

2020-11-23 12:15 UTC, wcy00000000000000 commented on src/scene_server/auth_server/app/discovery.go
> +	types.AddDiscoveryService(types.CC_MODULE_CORESERVICE)
auth server需要依赖cache service

2020-11-23 12:15 UTC, wcy00000000000000 commented on src/scene_server/datacollection/app/discovery.go
> +	types.AddDiscoveryService(types.CC_MODULE_CORESERVICE)
需要依赖cache service

2020-11-29 08:54 UTC, rentiansheng commented
### 需要修改的
- healthz 需要根据动态发现，返回依赖服务的监控情况
- 

### 需要新加

datacollection
- TopServer
- HostServer

### 需要删除

event_server
- CacheService

2021-05-19 03:59 UTC, closed without merging