修复存在多个开发商的资源池时authserver查询到错误的资源池ID的问题
Tencent/bk-cmdb pull request #4916
Opened 2020-11-30 08:09 UTC by wcy00000000000000

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2020-11-30 16:50 UTC, breezelxp requested changes

2020-11-30 16:50 UTC, breezelxp commented on src/scene_server/auth_server/logics/util.go
> +	rawBizID := bizResp.Data.Info[0][common.BKAppIDField]
这个直接给个初始化的值，是不是不合适？

2020-12-01 08:43 UTC, wcy00000000000000 commented on src/scene_server/auth_server/logics/util.go
> +	rawBizID := bizResp.Data.Info[0][common.BKAppIDField]
这个地方是在有多个开发商的资源池的时候尽量使用相同开发商的资源池，如果没有的话就用0开发商的（所以默认拿第一个资源池防止仅有0开发商的资源池的时候查不到）

2020-12-02 03:42 UTC, breezelxp approved these changes

2020-12-02 03:42 UTC, merged