清除自定义层级实例的default字段
Tencent/bk-cmdb pull request #4917
Opened 2020-11-30 11:53 UTC by wcy00000000000000

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2020-11-30 16:44 UTC, breezelxp requested changes

2020-11-30 16:44 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202011301723/remove_default_field.go
> +		instIDField := common.BKInstIDField
这两个可以挪到for外边定义吧？

2020-11-30 16:44 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202011301723/remove_default_field.go
> +			err := db.Table(tableName).Find(instFilter).Start(0).Limit(common.BKMaxPageSize).
start 一直是0？也不用更新？

2020-12-01 08:39 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.9.202011301723/remove_default_field.go
> +			err := db.Table(tableName).Find(instFilter).Start(0).Limit(common.BKMaxPageSize).
不用，因为设置了只更新exist的，所以删掉的已经不会出现在前面了

2020-12-02 03:39 UTC, breezelxp approved these changes

2020-12-02 06:38 UTC, breezelxp approved these changes

2020-12-02 06:38 UTC, merged