优化模型实例的创建和更新操作
Tencent/bk-cmdb pull request #4954
Opened 2020-12-11 14:21 UTC by fireyun

### 优化的功能:
- 优化模型实例的创建和更新操作

2020-12-14 07:14 UTC, rentiansheng requested changes

2020-12-14 07:20 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/instances/instance.go
> +		bizID, err := m.getBizIDFromInstance(kit, objID, origin, common.ValidCreate, 0)
是否应该用common.ValidUpdate

2020-12-14 07:37 UTC, breezelxp requested changes

2020-12-14 07:37 UTC, breezelxp commented on src/source_controller/coreservice/core/instances/validator_unique.go
> +	if hasUniqueField == true {
这个判断有点冗余

2020-12-14 07:37 UTC, breezelxp commented on src/source_controller/coreservice/core/instances/validator.go
> +		blog.Errorf("[validUpdateUnique] there're not unique constraint for %s, return, rid: %s", valid.objID, kit.Rid)
uniqueAttrs := make([]metadata.ObjectUnique, 0)

2020-12-14 07:37 UTC, breezelxp commented on src/source_controller/coreservice/core/instances/validator_unique.go
> +	for k, v := range updateData {
加个注释吧，为什么要这么做

2020-12-14 07:40 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/instances/validator_unique.go
> +	uniqueOpts, err := valid.getValidUniqueOptions(kit, instanceData, instanceManager)
为什么不直接用updateData判断是否有唯一校验的字段被更新？

2020-12-14 13:56 UTC, fireyun commented on src/source_controller/coreservice/core/instances/instance.go
> +	bizID, err := m.getBizIDFromInstance(kit, objID, inputParam.Data, common.ValidCreate, 0)
bizID单独拎出来作为批量操作时allValidators的key使用，防止重复创建validator

2020-12-14 14:36 UTC, fireyun commented on src/source_controller/coreservice/core/instances/instance_validate.go
> +		if validTye == common.ValidUpdate {
create直接fallthrough,走后面的case

2020-12-14 14:38 UTC, fireyun commented on src/source_controller/coreservice/core/instances/validator_unique.go
> +	uniqueOpts, err := valid.getValidUniqueOptions(kit, instanceData, instanceManager)
这里可以用，改了

2020-12-21 08:40 UTC, breezelxp commented on src/source_controller/coreservice/core/instances/validator_unique.go
> +	return false, nil
return false, make([]string, 0)

2020-12-21 12:16 UTC, breezelxp approved these changes

2020-12-21 12:17 UTC, merged