事件功能加固
Tencent/bk-cmdb pull request #4960
Opened 2020-12-14 02:35 UTC by wcy00000000000000

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2020-12-21 13:23 UTC, breezelxp requested changes

2020-12-21 13:23 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/watch.go
> +			return nil, kit.CCError.CCErrorf(common.CCErrCommParamsInvalid, "bk_start_from")
这个不能返回报错，应该把最后一个事件cursor返回了，不返回detail，然后让用户再继续watch。

2020-12-21 13:23 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/watch.go
> +			detail = *json.CutJsonDataWithFields(jsonStr, opts.Fields)
前面查的时候已经有了fields，这个cut的操作是不是可以不需要了？

2020-12-21 13:35 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/watch/watch.go
> +			detail = *json.CutJsonDataWithFields(jsonStr, opts.Fields)
查db的时候带了fields，查redis的时候没带（因为distributor要用update_fields和delete_fields）

2020-12-21 13:37 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/client.go
> +	if len(oids) == 0 {
这个判断应该挪出去，此外oids这个用deletedOids更准确些

2020-12-25 03:42 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/flow.go
> +	txnErr := f.txn.AutoRunTxn(context.Background(), true, http.Header{}, func() error {
这个不会出现分布式事务，直接用原生的事务处理方式

2020-12-25 03:42 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/client.go
> +			return false, nil, nil
这段逻辑抽成一个公共的逻辑，有几处都有相同的调用

2020-12-25 03:42 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/event.go
> +	}
多实例跑的时候会有问题

2021-01-06 09:07 UTC, breezelxp requested changes

2021-01-06 09:07 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/flow.go
> +		blog.Errorf("run flow, but start mongo session failed, err: %v", err)
日志带上f.key.Collection()

2021-01-06 09:07 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/flow.go
> +			blog.Errorf("run flow, but start mongo transaction failed, err: %v", err)
日志带上f.key.Collection()

2021-01-06 09:07 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/gc.go
> +		pageSize := 500
把这个调小到250

2021-01-06 14:52 UTC, breezelxp approved these changes

2021-01-06 14:53 UTC, merged