修复当主机有关联主线模型实例时，导出主机失败的问题
Tencent/bk-cmdb pull request #5064
Opened 2021-02-08 08:23 UTC by fireyun

### 修复的问题：
- 修复当主机有关联主线模型实例时，导出主机失败的问题

### 解决方式
因主机关联关系实例的导出只需要实例唯一校验字段，所以在toposerver增加查询所有模型实例唯一校验字段的接口
该接口只会返回唯一校验字段，不进行鉴权，即使主机关联了用户没权限的业务，也能正常导出关联关系excel表里的业务唯一字段

2021-02-19 08:55 UTC, wcy00000000000000 requested changes

2021-02-19 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst.go
> +		blog.Errorf("search model unique failed, cond: %s, error: %s, rid: %s", cond, err.Error(), ctx.Kit.Rid)
cond: %s 对应的不是字符串，或者你实际想用的是ErrorJSON？
下面还有一些这样的日志

2021-02-19 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst.go
> +	queryCond := data.SearchParams
为什么不直接用 queryCond := paraparse.SearchParams{} ?

2021-02-19 08:55 UTC, wcy00000000000000 commented on src/web_server/logics/association.go
> +		blog.ErrorJSON(" fetchInstAssocationData failed, GetInstUniqueFields err:%v, option: %s, rid: %s", err, option, rid)
fetchInstAssocationData 里面的Assocation应该是Association

2021-02-19 08:55 UTC, wcy00000000000000 commented on src/web_server/logics/association.go
> +		"fields": dbFields,
dbFields就是唯一校验里的字段+id字段，后面又重新查了一遍和这里重复了，可以去掉前面获取dbFields的操作

2021-02-22 08:38 UTC, fireyun commented on src/scene_server/topo_server/service/inst.go
> +	queryCond := data.SearchParams
是为了获取入参里的查询条件，以获取指定条件的实例唯一字段值

2021-02-22 09:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst.go
> +	queryCond := data.SearchParams
我的意思是data := struct {
		paraparse.SearchParams `json:",inline"`
	}{}

2021-03-01 07:52 UTC, breezelxp approved these changes

2021-03-01 07:53 UTC, merged