optimize: change the watch event startup mode with asynchronize policy.
Tencent/bk-cmdb pull request #5111
Opened 2021-03-11 14:50 UTC by breezelxp

### 优化的功能:
- change the watch event startup mode with asynchronize policy.

2021-03-12 02:44 UTC, wcy00000000000000 requested changes

2021-03-12 02:44 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/flow.go
> +		}
cursorMap仅在这里判断了，没有赋值

2021-03-12 02:44 UTC, wcy00000000000000 commented on src/storage/stream/event/list_watch.go
> +				err := opts.WatchFatalErrorCallback(&types.TimeStamp{Sec: startAtTime})
这里不是指针

2021-03-12 09:02 UTC, breezelxp commented on src/storage/stream/event/list_watch.go
> +				err := opts.WatchFatalErrorCallback(&types.TimeStamp{Sec: startAtTime})
已调整

2021-03-15 08:15 UTC, wcy00000000000000 submitted a review, later dismissed
LGTM

2021-03-15 13:33 UTC, merged