V3.5.x
Tencent/bk-cmdb pull request #5117
Opened 2021-03-15 08:48 UTC by chalice-1831

minor 将get_all_users接口替换成最新的list_users接口
bugfix 修复非主机业务资源下点击列表排序无法排序问题

2021-03-15 08:48 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5117) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-cmdb?pullRequest=5117) it.</sub>

2021-03-23 11:45 UTC, chalice-1831 commented
#5139

2021-03-23 11:46 UTC, chalice-1831 commented
#5139 v3.5.x 更换接口以及功能修复

2021-04-15 03:53 UTC, breezelxp requested changes

2021-04-15 03:53 UTC, breezelxp commented on src/scene_server/datacollection/pid/datacollection.exe.pid
> +16344
这几个pid文件是什么文件? 这不能提上来吧？

2021-04-20 13:44 UTC, breezelxp approved these changes

2021-04-20 13:44 UTC, merged