V3.9.x
Tencent/bk-cmdb pull request #5141
Opened 2021-03-23 12:10 UTC by chalice-1831

### 新加的功能:
- 开放不同自定义层级下集群同名限制
### 修复的问题：
- 模型关联关系中n:n模型自关联出现已被关联对象仍可关联关联发起对象

2021-03-23 12:10 UTC, chalice-1831 commented
#5140 模型自关联问题以及不同层级下同名集群创建限制

2021-04-08 08:24 UTC, chalice-1831 commented on src/scene_server/admin_server/imports.go
> +	_ "configcenter/src/scene_server/admin_server/upgrader/y3.9.202103231516"
修改改好了

2021-04-08 08:35 UTC, breezelxp requested changes

2021-04-08 08:35 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104081621/change_set_unique_index.go
> +			}
走到这里，是不是直接return nil就可以了？不用再空跑了？

另外，新加索引的这个，如果不存在idxUniqueSetName这个索引，你也不加了？不行吧？

2021-04-08 08:38 UTC, joe511230 submitted a review, later dismissed

2021-04-08 08:45 UTC, chalice-1831 commented on src/ui/package.json
> +    "2015": "0.0.1",
这个已经去除了

2021-04-08 08:45 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.9.202104081621/change_set_unique_index.go
> +	"configcenter/src/storage/dal/types"
import顺序

2021-04-08 08:48 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +	}
为什么要多查一次？应该按传入的条件直接查了就返回吧

2021-04-08 08:51 UTC, wcy00000000000000 commented
vendor包里的那些文件不要改

2021-04-08 11:29 UTC, chalice-1831 commented on src/scene_server/topo_server/service/association.go
> +	}
自关联的话他会忽略了首尾唯一标识的问题，例如bk_switch_connect_bk_switch这个关联，会导致若s1关联了s2，s2还能选择关联s1。会出现回环

2021-04-08 11:49 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +	}
这个跟那个无关，它就是一个查询接口而已，你如果要对自关联的查出双向的那应该改condition而非查询接口

2021-04-15 03:51 UTC, breezelxp requested changes

2021-04-15 03:51 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/change_set_unique_index.go
> +		}
这个逻辑不够严谨：
1. 有parent id这个字段的索引，不一定是唯一索引，不能因为有这个，就不管了。
2. 有唯一索引的场景，是parent id + set name。
3. 这个操作要是可重入的。

2021-04-15 03:51 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/pkg.go
> +	blog.Infof("start execute y3.9.202104091100")
加一下补充说明，说明这个upgrader是做什么的。

2021-04-15 06:49 UTC, chalice-1831 commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/pkg.go
> +	blog.Infof("start execute y3.9.202104091100")
已添加

2021-04-15 06:49 UTC, chalice-1831 commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/change_set_unique_index.go
> +		}
已修改，请检查

2021-04-20 13:42 UTC, breezelxp requested changes

2021-04-20 13:42 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/change_set_unique_index.go
> +			}
有这个判断条件就可以了，为什么要带if _, ok := index.Keys[common.BKParentIDField];这个判断条件？

2021-04-20 13:42 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/change_set_unique_index.go
> +	idxUniqueSetName := "idx_unique_parentID_setName"
这个定义了名字，为什么不在初始化index的时候，也有这个变量？本来就是同一个意思，是不是？

2021-04-20 13:42 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/pkg.go
> +	blog.Infof("start execute y3.9.202104091100")
加什么了?

2021-04-21 03:48 UTC, chalice-1831 commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/change_set_unique_index.go
> +			}
idxUniqueSetName是我自己定义的，判断是否有这个唯一索引现在想的是判断索引key长度是否为2 是否为unique然后在判断key是否为parentid和setnameid，这样能保证没有相同功能的索引创建

2021-04-21 05:44 UTC, chalice-1831 commented on src/scene_server/admin_server/upgrader/y3.9.202104091100/change_set_unique_index.go
> +	idxUniqueSetName := "idx_unique_parentID_setName"
已修改

2021-04-21 07:51 UTC, breezelxp requested changes

2021-04-21 07:51 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202104211151/change_set_unique_index.go
> +		}
把这部分代码删除，然后把isCreateUniqueSetName = false下移到L64行的if内，保持二者判断条件一致，是不是更合理？

2021-04-21 09:26 UTC, chalice-1831 commented on src/scene_server/admin_server/upgrader/y3.9.202104211151/change_set_unique_index.go
> +		}
已按照沟通的结果修改

2021-04-21 11:47 UTC, breezelxp approved these changes
LGTM

2021-04-21 11:48 UTC, merged