fix: DeleteAssociationInstBatch function adapt to new DB-model
Tencent/bk-cmdb pull request #5202
Opened 2021-04-15 03:52 UTC by Dravening

### 修复的问题：
- 批量删除关联关系实例--函数适配拆表后的数据库模型。

2021-04-15 05:09 UTC, fireyun commented on src/scene_server/topo_server/core/operation/association.go
> +	}
这个要么不比较不报错（不会误删或产生脏数据，只会删存在的实例id），要么提供具体不存在的错误实例id列表供调用方调整入参

2021-04-21 03:45 UTC, breezelxp requested changes

2021-04-21 03:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association.go
> -	cond := condition.CreateCondition().Field(common.BKFieldID).In(asstIDList)
objID这个入参不用了，是不是可以不用传了？

2021-04-21 03:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association.go
> -	cond := condition.CreateCondition().Field(common.BKFieldID).In(asstIDList)
另外，这个参数的目的也是为了校验asstIDList，中的关系是不是都是关联到或者被关联到的id，校验数据的合法性，不传这个参数，是不是就校验不了了？

2021-04-21 03:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association.go
> +	if len(assInfoResult.Data) != len(objAsstList) {
这个校验是有必要的

2021-04-21 06:37 UTC, Dravening commented on src/scene_server/topo_server/core/operation/association.go
> -	cond := condition.CreateCondition().Field(common.BKFieldID).In(asstIDList)
老哥。。这里是toposerver啊，objID在这里是肯定要用的啊。

2021-04-21 06:43 UTC, Dravening commented on src/scene_server/topo_server/core/operation/association.go
> -	cond := condition.CreateCondition().Field(common.BKFieldID).In(asstIDList)
还有，下边那个校验objID为空的逻辑是我上个pr写的，当时还没分表。
是为了适配另一个场景层的逻辑，做的校验。
那个场景层没写objID，不加objID也能查表。
--------------------------------------------------
现在情况不同了，分表了，不加objID不能查表了，所以这个objID是在接口入参做校验，不能存在不填的情况。

2021-04-21 06:43 UTC, Dravening commented on src/scene_server/topo_server/core/operation/association.go
> -	cond := condition.CreateCondition().Field(common.BKFieldID).In(asstIDList)
还有，下边那个校验objID为空的逻辑是我上个pr写的，当时还没分表。
是为了适配另一个场景层的逻辑，做的校验。
那个场景层没写objID，不加objID也能查表。
--------------------------------------------------
现在情况不同了，分表了，不加objID不能查表了，所以这个objID是在接口入参做校验，不能存在不填的情况。

2021-04-21 07:43 UTC, Dravening commented on src/scene_server/topo_server/core/operation/association.go
> +	}
1035行这个地方不是校验入参的，是校验模型关联是否存在的。这个报错属于脏数据问题了。
你说的是在1011行，我加一下报错具体的实例id。

2021-04-21 12:44 UTC, breezelxp approved these changes

2021-04-21 12:44 UTC, merged