模型“唯一校验”规则优化调整
Tencent/bk-cmdb pull request #5241
Opened 2021-05-08 12:32 UTC by wcy00000000000000

### 优化的功能:
- 模型“唯一校验”规则优化调整

close #5240

2021-05-12 13:47 UTC, breezelxp requested changes

2021-05-12 13:47 UTC, breezelxp commented on src/common/index/index.go
> +	case common.FieldTypeSingleChar, common.FieldTypeEnum, common.FieldTypeDate, common.FieldTypeList:
组织字段类型是不是也是string？

2021-05-12 13:47 UTC, breezelxp commented on src/source_controller/coreservice/core/model/unique_crud.go
> +				properties, err := m.getUniqueProperties(kit, objID, u.Keys, u.MustCheck)
这里有一个must_check的判断，去掉

2021-05-13 06:56 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/unique.go
> +				fmt.Printf("attribute(%d) type %s is invalid\n", property.ID, property.PropertyType)
我看了下这个函数checkObjectUnique的实现和上层调用，上层只有一个commandline函数调用。这个实现不太友好，所有的异常，不要只打到标准输出里，应该直接返回error,然后在函数调用的地方输出到标准输出里，这个函数里的fmt.Printf全部改成以error返回。

2021-05-13 06:56 UTC, breezelxp commented on src/source_controller/coreservice/core/model/unique_crud.go
> +func (m *modelAttrUnique) checkUniqueRuleExist(kit *rest.Kit, objID string, ruleID uint64, keys []metadata.UniqueKey) error {
把这个校验规则的issue链接也贴一下。 https://github.com/Tencent/bk-cmdb/issues/5240

2021-05-13 06:56 UTC, breezelxp commented on src/source_controller/coreservice/core/model/unique_crud.go
>  		keysMap[key.ID] = true
这个地方是不是顺便校验下，传的这个keys里边有没有重复的，如果有重复的，也要报错？

2021-05-13 07:51 UTC, wcy00000000000000 commented on src/common/index/index.go
> +	case common.FieldTypeSingleChar, common.FieldTypeEnum, common.FieldTypeDate, common.FieldTypeList:
组织是不允许在唯一校验里的

2021-05-13 07:55 UTC, wcy00000000000000 commented on src/tools/cmdb_ctl/cmd/unique.go
> +				fmt.Printf("attribute(%d) type %s is invalid\n", property.ID, property.PropertyType)
这个不可以的哦，这个是检查升级前的实例是否满足唯一校验的小工具，所以要在所有有错误的地方输出错误，不然每次只返回一个错误的话用户要多检查好多次

2021-05-18 13:57 UTC, breezelxp approved these changes
LGTM

2021-05-18 13:57 UTC, merged