通用模型实例拆分后IAM动态资源注册管理和资源池主机、通用模型实例支持按枚举属性鉴权
Tencent/bk-cmdb pull request #5254
Opened 2021-05-14 12:29 UTC by fireyun

### 新加的功能:
- 通用模型实例拆分后的iam动态资源注册管理
- 通用模型实例拆分后的实例视图和反向资源拉取调整
- 资源池主机和通用模型实例支持按枚举属性鉴权

2021-05-18 08:01 UTC, wcy00000000000000 requested changes

2021-05-23 10:08 UTC, fireyun commented on src/ac/iam/iam.go
> +	Client *iamClient
后面的调整有用到了

2021-05-23 10:10 UTC, fireyun commented on src/scene_server/auth_server/app/server.go
> +		acIam, err := iam.NewIam(nil, authConf, engine.Metric().Registry())
已调整

2021-05-23 10:11 UTC, fireyun commented on src/scene_server/auth_server/service/pull_resource.go
> +	blog.V(4).Infof("pull resource param:%s", pullParam)
这个能打印出原始的反向资源拉取接口入参，方便排查问题

2021-05-23 10:11 UTC, fireyun commented on src/scene_server/auth_server/service/syncAction.go
> +func (s *AuthService) SyncIAMModelResources(kit rest.Kit) error {
已调整

2021-06-01 11:49 UTC, closed without merging