迁移存量模型实例的权限
Tencent/bk-cmdb pull request #5279
Opened 2021-05-24 12:39 UTC by wcy00000000000000

### 新加的功能:
- 迁移存量模型实例的权限

close #5278

2021-06-22 07:52 UTC, breezelxp requested changes

2021-06-22 07:52 UTC, breezelxp commented on src/ac/iam/iam.go
> +func (i Iam) migrateModelInstancePermission(ctx context.Context, action ActionID, db dal.DB) error {
补充下注释，另外通过ctx带一个rid过来，把调用串起来。

2021-06-22 07:52 UTC, breezelxp commented on src/ac/iam/iam.go
> +		}
确认下这个分页的逻辑对不对

2021-06-22 07:52 UTC, breezelxp commented on src/ac/iam/iam.go
> +					err := i.batchGrantInstanceAuth(ctx, policyRes.Subject, policyRes.ExpiredAt, action, nil, id)
重复授权会不会有问题？

2021-06-22 07:52 UTC, breezelxp commented on src/ac/iam/iam.go
> +				if err := db.Table(common.BKTableNameBaseInst).Find(instanceFilter).Fields(common.BKInstIDField,
查错表了，这个应该先查mapping表，再进行其它处理。

2021-06-22 07:52 UTC, breezelxp commented on src/ac/iam/iam.go
> +	if actionID == "create_sys_instance" {
把这个特殊逻辑去掉

2021-06-22 07:52 UTC, breezelxp commented on src/ac/iam/iam.go
>  	systemResp, err := i.client.GetSystemInfo(ctx)
systemResp的判断逻辑有问题，可能会出现nil引用导致panic。

2021-06-29 13:17 UTC, wcy00000000000000 commented on src/ac/iam/iam.go
>  	systemResp, err := i.client.GetSystemInfo(ctx)
这个不会返回nil的，不过可以加一个兼容逻辑

2021-06-29 13:18 UTC, wcy00000000000000 commented on src/ac/iam/iam.go
> +func (i Iam) migrateModelInstancePermission(ctx context.Context, action ActionID, db dal.DB) error {
这个是upgrader调的，没有rid，要生成一个吗？

2021-06-29 14:09 UTC, wcy00000000000000 commented on src/ac/iam/iam.go
> +	for page := int64(1); page < count/pageSize || count == -1; page++ {
![image](https://user-images.githubusercontent.com/40779709/123812348-96fbc880-d926-11eb-9def-5c954539e36b.png)
文档上写的默认为1

2021-06-29 14:14 UTC, wcy00000000000000 commented on src/ac/iam/iam.go
> +	if actionID == "create_sys_instance" {
这个没法去掉，创建操作是按模型授权的，和别的不一样

2021-06-29 14:21 UTC, wcy00000000000000 commented on src/ac/iam/iam.go
> +					err := i.batchGrantInstanceAuth(ctx, policyRes.Subject, policyRes.ExpiredAt, action, nil, id)
权限中心说会先判断一下

2021-06-30 14:01 UTC, wcy00000000000000 commented on src/ac/iam/client.go
> +	// http Client instance
TODO: 还原回小写

2021-06-30 14:12 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.10.202106301057/migrate_iam_sysinstances.go
> +		blog.ErrorJSON("get all custom objects failed, err:%s", err)
Errorf

2021-06-30 14:12 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.10.202106301057/migrate_iam_sysinstances.go
> +		blog.ErrorJSON("sync iam system instances failed, err:%s", err)
Errorf

2021-08-31 13:17 UTC, wcy00000000000000 reviewed
upgrader 改成9月7日

2021-09-10 07:31 UTC, breezelxp approved these changes

2021-09-10 07:31 UTC, merged