V3.10.x 添加批量创建通用模型实例关联关系接口
Tencent/bk-cmdb pull request #5293
Opened 2021-05-26 06:44 UTC by chalice-1831

### 新加的功能:
- 批量创建通用模型实例关联关系接口
issue #5292

2021-05-31 11:52 UTC, mrmgxxxx commented on src/ac/parser/topolatest.go
> +			InstID := instanceMap[common.BKInstIDField]
变量名小写

2021-05-31 11:52 UTC, mrmgxxxx commented on src/ac/parser/topolatest.go
> +			AsstInstID := instanceMap[common.BKAsstInstIDField]
变量名小写

2021-05-31 11:52 UTC, mrmgxxxx commented on src/common/metadata/association.go
> +	CreatedID []int64                  `json:"created_id"`
这个和批量创建实例的struct定义风格都不一样的，那边叫SuccessCreated这边叫CreatedID, 这个是不是可以统一下

2021-05-31 11:52 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +		switch result.Data[0].Mapping {
这里直接使用你前面引出来的objectAsst，不要再引用result.Data 这跨度太大还容易和for循环里的混淆

2021-05-31 11:52 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +		instanceAssociationID := int64(item.ID)
instAsstID

2021-05-31 11:52 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +			return nil, err
错误码处理

2021-05-31 11:52 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +		return nil, err
错误码处理

2021-06-01 03:36 UTC, chalice-1831 commented on src/ac/parser/topolatest.go
> +			AsstInstID := instanceMap[common.BKAsstInstIDField]
已修改

2021-06-01 03:36 UTC, chalice-1831 commented on src/common/metadata/association.go
> +	CreatedID []int64                  `json:"created_id"`
已修改

2021-06-01 03:36 UTC, chalice-1831 commented on src/scene_server/topo_server/core/operation/association.go
> +		switch result.Data[0].Mapping {
已修改

2021-06-01 03:36 UTC, chalice-1831 commented on src/scene_server/topo_server/core/operation/association.go
> +			return nil, err
已修改

2021-06-01 03:36 UTC, chalice-1831 commented on src/scene_server/topo_server/core/operation/association.go
> +		return nil, err
已修改

2021-06-03 02:33 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +	if len(request.Details) == 0 || len(request.Details) > 200 {
参数校验是不是可以前置

2021-06-03 02:33 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +		res, err := assoc.clientSet.CoreService().Instance().ReadInstance(kit.Ctx, kit.Header, objID, checkInstParams)
判断res的result

2021-06-03 02:33 UTC, mrmgxxxx commented on src/scene_server/topo_server/core/operation/association.go
> +		res, err = assoc.clientSet.CoreService().Instance().ReadInstance(kit.Ctx, kit.Header, asstObjID, checkInstParams)
同上判断res的result

2021-06-03 02:35 UTC, rentiansheng requested changes

2021-06-03 02:35 UTC, rentiansheng commented on src/ac/parser/topolatest.go
> +		modelFilter := mapstr.MapStr{
asst  这个是不是需要判断下， 如果没有数组元素 这里就panic了

2021-06-03 02:35 UTC, rentiansheng commented on src/common/metadata/association.go
> +	ExistErr       []AssociationInstDetails `json:"err_non_existent"`
AssociationInstDetails 没看到错误提示的信息

2021-06-03 02:35 UTC, rentiansheng commented on src/scene_server/topo_server/core/operation/association.go
> +	createResult, err := assoc.clientSet.CoreService().Association().CreateInstAssociationBatch(kit.Ctx, kit.Header, &input)
没有判断 createResult 返回的error

2021-06-03 02:35 UTC, rentiansheng commented on src/scene_server/topo_server/core/operation/association.go
> +func (assoc *association) CreateAssociationInstBatch(kit *rest.Kit, request *metadata.CreateManyInstAsstRequest) (*metadata.CreateManyInstAsstResultDetail, error) {
新加的函数，返回值中的error 都需要使用ccerrors , 这个改下。 只有用cc error ， 错误信息才能提示出来的

2021-06-03 02:42 UTC, mrmgxxxx commented on src/common/metadata/association.go
> +	ExistErr       []AssociationInstDetails `json:"err_non_existent"`
这个地方的设计是按照两个列表用途或者说含义设计的单独实例列表？

2021-06-16 07:48 UTC, chalice-1831 commented on src/ac/parser/topolatest.go
> +		modelFilter := mapstr.MapStr{
上面的函数调用规避了这个问题，没有数字直接抛出异常了

2021-06-16 13:36 UTC, mrmgxxxx commented on src/source_controller/coreservice/core/association/instance.go
> +	cond := &metadata.QueryCondition{Condition: map[string]interface{}{common.AssociationObjAsstIDField: ObjAsstID}}
cond定义完下面再*引用一次，直接写非指针的不就好了

2021-06-16 13:36 UTC, mrmgxxxx commented on src/source_controller/coreservice/core/association/instance.go
> +	case string(metadata.OneToManyMapping):
如果是OneToManyMapping类型是不是不需要查询instCount了？

2021-06-16 13:36 UTC, mrmgxxxx commented on src/source_controller/coreservice/core/association/instance.go
> -		item.OwnerID = kit.SupplierAccount
带上

2021-06-17 02:26 UTC, chalice-1831 commented on src/ac/parser/topolatest.go
> +		for _, instanceItem := range instanceArray {
instance是gjson.result类型不能直接range，还是得instances.array()

2021-06-17 03:06 UTC, chalice-1831 commented on src/scene_server/topo_server/core/operation/association.go
> +	if request.ObjectAsstID[:len(request.ObjectID)] != request.ObjectID {
增加了参数校验validate

2021-06-17 07:50 UTC, closed without merging