模板/拓扑节点名称校验规则更新
Tencent/bk-cmdb pull request #5294
Opened 2021-05-26 08:12 UTC by wcy00000000000000

### 优化的功能:
- 模板/拓扑节点名称校验规则更新

2021-05-27 07:09 UTC, breezelxp requested changes

2021-05-27 07:09 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202105261459/update_config_admin.go
> +func updateConfigAdmin(ctx context.Context, db dal.RDB, conf *upgrader.Config) error {
这个不能这么更新，要考虑到用户已经更新了存量的数据，你这一改，用户的配置就全没了。

2021-05-27 07:09 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202105261459/pkg.go
> +	upgrader.RegistUpgrader("y3.9.202105261459", upgrade)
这个要提一个新的PR到v3.10，版本号是y3.10的

2021-05-27 07:10 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.9.202105261459/update_config_admin.go
> +func updateConfigAdmin(ctx context.Context, db dal.RDB, conf *upgrader.Config) error {
更新的数据在johny写的那段逻辑里有处理的

2021-06-03 08:37 UTC, breezelxp approved these changes

2021-06-03 08:37 UTC, merged