mongodb事件监听遇到cursor重复时查找并去除重复的事件
Tencent/bk-cmdb pull request #5316
Opened 2021-06-01 06:53 UTC by wcy00000000000000

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2021-06-01 12:45 UTC, breezelxp requested changes

2021-06-01 12:45 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/flow.go
> +			if len(chainNodes) == 1 {
这个条件是不是应该是<=1 ?

2021-06-01 12:45 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/flow.go
> +			}
for 循环外，是不是还是得有一个兜底的？ return f.doInsertEvents(chainNodes[1:], lastTokenData, rid) ？

2021-06-01 12:47 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/flow.go
> +			if len(chainNodes) == 1 {
前面判断了==0

2021-06-02 02:58 UTC, breezelxp approved these changes

2021-06-02 02:58 UTC, merged