cmdb小工具增加对redis的操作的支持
Tencent/bk-cmdb pull request #5350
Opened 2021-06-10 13:27 UTC by wjyfelen

### 新加的功能:
- cmdb小工具增加对redis的操作的支持  #5343
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2021-06-15 06:49 UTC, breezelxp requested changes

2021-06-15 06:49 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +	"fmt"
顺序

2021-06-15 06:49 UTC, breezelxp commented on src/tools/cmdb_ctl/app/config/config.go
> +	RedisAddr     string
你这个写法不支持redis sentinal部署使用

2021-06-15 06:49 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +		Use:   "del",
scan-del

2021-06-15 06:49 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +func runRedisDel(conf *redisOperation) error {
这个命令的实现不符合预期，这个命令的意思是把用scan扫到的数据，删除了。不是说给个key-value删除，如果是这种的，直接用redis的命令就可以了，不用我们封装了。

2021-06-15 07:15 UTC, wjyfelen commented on src/tools/cmdb_ctl/cmd/redis.go
> +	"fmt"
done

2021-06-15 09:02 UTC, wjyfelen commented on src/tools/cmdb_ctl/cmd/redis.go
> +func runRedisDel(conf *redisOperation) error {
done

2021-06-15 09:02 UTC, wjyfelen commented on src/tools/cmdb_ctl/cmd/redis.go
> +		Use:   "del",
done

2021-06-22 02:59 UTC, breezelxp requested changes

2021-06-22 02:59 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +	}
这段逻辑不能保证完全删除数据，scan不会一次返回所有的数据。

2021-06-22 02:59 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +	fmt.Printf("cursor is %d \n", cursor)
这段逻辑调整下，循环跑scan，直到扫描到数据大于count后再退出。

2021-06-22 02:59 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +	redisConfig, err := cc.Redis("redis")
redis有很多个，这种写法就是直接把redis写死了，但不一定是对这个redis操作。所以redis的地址，可以直接指定，不要用配置的。

2021-06-24 09:53 UTC, wjyfelen commented on src/tools/cmdb_ctl/cmd/redis.go
> +	fmt.Printf("cursor is %d \n", cursor)
done

2021-06-24 09:53 UTC, wjyfelen commented on src/tools/cmdb_ctl/cmd/redis.go
> +	redisConfig, err := cc.Redis("redis")
done

2021-06-24 09:53 UTC, wjyfelen commented on src/tools/cmdb_ctl/cmd/redis.go
> +	}
done

2021-06-27 11:56 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +				fmt.Printf("keys is begin :\n")
这个直接在151行打，是不是也可以？不用再判断了？

2021-06-27 11:56 UTC, breezelxp commented on src/tools/cmdb_ctl/cmd/redis.go
> +				fmt.Printf("%v \n", v)
key的量可能非常大，所以不用打key了，打每次删了多少key有个滚动就行了

2021-06-29 03:30 UTC, breezelxp approved these changes

2021-06-29 03:30 UTC, merged