fix: 并发场景下，概率性出现设置实例的关联关系失效
Tencent/bk-cmdb pull request #5402
Opened 2021-06-24 07:00 UTC by wjyfelen

### 新加的功能:
- 
### 优化的功能:
- xxxx
### 修复的问题：
- 并发场景下，概率性出现设置实例的关联关系失效 #5401

2021-06-27 11:36 UTC, breezelxp requested changes

2021-06-27 11:36 UTC, breezelxp commented on resources/errors/common/default/core_service.json
> +    "1113051": "其他人正在做此关联关系操作",
改一下，"关联关系约束不匹配"

2021-06-27 11:36 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +		blog.Errorf("request(%s): it is to search associations by the condition (%#v), error info is %s", kit.Rid, condCheckModel.ToMapStr(), err.Error())
rid都放到最后，另外，这些异常，不返回是什么原因?包括下面的那些异常

2021-06-27 11:36 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +	if mappingType == metadata.OneToOneMapping {
加锁的这段逻辑应该封装到一个独立的函数里去处理比较合适。

2021-06-27 11:36 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +		locked, err := locker.MLock(lock.StrFormat(mappingKey1), lock.StrFormat(mappingKey2))
加锁要考虑几个问题:
1. 一定要带ttl。
2. 如果已经被锁，是不是可以在秒级的时间内自动重试，更友好？
3. 锁的粒度要足够小

2021-06-27 11:36 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +			blog.ErrorJSON("get mlock error. err:%s, instkey:%s,asstInstkey:%s, rid:%s", err.Error(),
不要滥用ErrorJSON打日志

2021-06-27 11:36 UTC, breezelxp commented on src/source_controller/coreservice/core/association/instance.go
> +	} else if metadata.AssociationMapping(mappingType) == metadata.OneToManyMapping {
换成switch是不是更合适？

2021-06-27 11:36 UTC, breezelxp commented on src/common/lock/lock.go
> +func (l *lock) MLock(values ...StrFormat) (locked bool, err error) {
1. 补充注释
2. 是不是应该是kv pair对？

2021-06-28 03:00 UTC, wjyfelen commented on resources/errors/common/default/core_service.json
> +    "1113051": "其他人正在做此关联关系操作",
done

2021-06-28 03:01 UTC, wjyfelen commented on src/source_controller/coreservice/core/association/instance.go
> +		blog.Errorf("request(%s): it is to search associations by the condition (%#v), error info is %s", kit.Rid, condCheckModel.ToMapStr(), err.Error())
异常场景之前想法是统一走不加锁 ，所以mappingType =metadata.ManyToManyMapping ， 这里注释里注明了//Abnormal scene  no lock

2021-06-28 03:03 UTC, wjyfelen commented on src/source_controller/coreservice/core/association/instance.go
> +		blog.Errorf("request(%s): it is to search associations by the condition (%#v), error info is %s", kit.Rid, condCheckModel.ToMapStr(), err.Error())
coreservice中的core里面很多函数都是rid放在了最前面，这个需求统一改一下么

2021-06-28 03:04 UTC, wjyfelen commented on src/source_controller/coreservice/core/association/instance.go
> +			blog.ErrorJSON("get mlock error. err:%s, instkey:%s,asstInstkey:%s, rid:%s", err.Error(),
done

2021-06-28 05:59 UTC, rentiansheng requested changes

2021-06-28 05:59 UTC, rentiansheng commented on src/common/lock/lock.go
> +func (l *lock) MLock(values ...StrFormat) (locked bool, err error) {
是不是需要写一个MUnlock 保持一一对应， 容易理解

2021-06-28 05:59 UTC, rentiansheng commented on src/source_controller/coreservice/core/association/instance.go
> +		blog.Errorf("request(%s): it is to search associations by the condition (%#v), error info is %s", kit.Rid, condCheckModel.ToMapStr(), err.Error())
用blog.ErrorJSON输出日志比较好

2021-06-28 05:59 UTC, rentiansheng commented on src/source_controller/coreservice/core/association/instance.go
> +
这个是故意这么写的吗？ 是不是可以改下上面的else if

2021-06-28 05:59 UTC, rentiansheng commented on src/source_controller/coreservice/core/association/instance.go
> +				fmt.Sprintf("%s%s", common.BKCacheKeyV3Prefix, mappingKey1),
key的生成，封装一个特定的函数

2021-06-28 05:59 UTC, rentiansheng commented on src/source_controller/coreservice/core/association/instance.go
> +	} else if metadata.AssociationMapping(mappingType) == metadata.OneToManyMapping {
err 的判断 if  的else 与业务逻辑放在一起不合适吧

2021-06-28 12:38 UTC, rentiansheng approved these changes

2021-06-28 12:38 UTC, rentiansheng submitted a review, later dismissed
通过

2021-07-01 12:03 UTC, breezelxp approved these changes

2021-07-01 12:40 UTC, merged