feature 优化集群模板更新中同步状态判断逻辑并去除集群模板表以及集群表的version字段
Tencent/bk-cmdb pull request #5409
Opened 2021-06-28 12:52 UTC by chalice-1831

### 新加的功能:
- 去除集群模板及集群表中的version字段
### 优化的功能:
- 优化集群模板同步状态判断逻辑

优化后接口调用时间显著提高
单机测试单一场景下：
500条集群实例场景下 | 修改后 | 修改前
-- | -- | --
删除280个服务实例更新耗时 | 4.29s | 保存失败，1.3min后返回错误信息
增加280个服务实例更新耗时 | 4.47s | 保存失败，1.4min后返回错误信息

issue #5408 

*暂未完成全部代码检查及单元测试

2021-06-29 08:25 UTC, breezelxp requested changes

2021-06-29 12:16 UTC, chalice-1831 commented on src/scene_server/topo_server/core/settemplate/sync_status.go
> +		setID, err := getSetIDFromTaskDetail(kit, APITask)
APITask里没有单独的setid字段，查询条件都是通过sprintf的方式将setid和前面的字段组合起来才成为flag然后到表中查询，这里要拿setid的话就只好把setid前面的字段切掉，拿到setid

2021-06-30 06:07 UTC, fireyun commented on src/source_controller/coreservice/service/set_template.go
> +		go func(kit *rest.Kit, setID int64, setStatus metadata.SetTemplateSyncStatus) {
漏了wg.Done()和对pipeline的接收操作

2021-06-30 12:40 UTC, breezelxp requested changes

2021-06-30 12:40 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202106301723/drop_set_template_version_column.go
> +}
这两个实现有问题吧？你这个for循环没用吧，是不是应该用DropColumns，带上filter分批去更新？

2021-06-30 12:40 UTC, breezelxp commented on src/scene_server/topo_server/core/settemplate/settemplate.go
> +		blog.ErrorJSON("check set whether need sync failed, set: %+v, err: %s, rid: %s",
这里不就方用ErrorJSON，errorf就可以了

2021-06-30 12:40 UTC, breezelxp commented on src/scene_server/topo_server/service/set_template.go
> +			blog.Errorf("set id is not int, err: %s, rid: %s", ctx.Kit.Rid)
err漏写了？

2021-06-30 12:40 UTC, breezelxp commented on src/scene_server/topo_server/service/set_template.go
> +		setStatus, _ := setSyncStatus[setID]
这个应该和下面的合到一块儿写？
setStatus, exist := setSyncStatus[setID]
if !exist {
  continue
}

把这个去掉？
if setStatus == nil {
	continue
}

2021-06-30 12:40 UTC, breezelxp commented on src/scene_server/topo_server/service/set_template.go
> +	taskDetail, err := s.Core.SetTemplateOperation().GetLatestSyncTaskDetail(kit, setIDs)
即然这个函数 getSetSyncStatus 里边只调用了一个函数，那直接把这个函数去了，外边直接调用不是更简单？还少了一次调用？

2021-06-30 12:40 UTC, breezelxp commented on src/source_controller/coreservice/service/set_template.go
> +	pipeline := make(chan bool, 5)
pipeline := make(chan struct{}, 5)

2021-06-30 13:09 UTC, breezelxp commented on src/scene_server/topo_server/core/settemplate/sync_status.go
> +		NeedSync := diffModuleServiceTpl(serviceTemplateCnt, serviceTemplateMap, setModulesCnt, module)
needSync

2021-06-30 13:09 UTC, breezelxp commented on src/scene_server/topo_server/core/settemplate/sync_status.go
> +	checkResult := make(map[int64]bool, len(setIDs))
checkResult := make(map[int64]bool, len(setModules))

2021-06-30 13:09 UTC, breezelxp commented on src/scene_server/topo_server/core/settemplate/sync_status.go
> +	checkNeedSyncResult, err := st.isSyncRequired(kit, bizID, setTemplateID, setID)
checkNeedSyncResult -> needSyncs

2021-07-01 03:30 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202107011114/drop_set_template_version_column.go
> +			blog.Errorf("count table %s failed, err: %s", common.BKTableNameSetTemplate, err.Error())
count ?

2021-07-01 03:30 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202107011114/drop_set_template_version_column.go
> +			blog.Errorf("drop column failed, field:%s, err:%v", "version", err)
把表名带上，另外把version直接放进去，不用格式化是不是可以？

2021-07-01 03:30 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202107011114/drop_set_template_version_column.go
> +		setTpls := make([]map[string]interface{}, 0)
加一个打屏的日志，这样在升级的时候就知道执行到那儿了，到那儿出错了。你看现在的日志，任何一个地方报错了，都不知道是在干什么的时候报错了。

2021-07-01 03:30 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202107011114/drop_set_template_version_column.go
> +func dropSetTplVersionColumn(ctx context.Context, db dal.RDB, conf *upgrader.Config) error {
按上面的方式也调整下

2021-07-01 03:30 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.9.202107011114/pkg.go
> +
这两个函数执行成功后，都加一个成功的日志

2021-07-01 09:44 UTC, breezelxp commented on src/scene_server/task_server/logics/task.go
> +	if input.Filter != nil {
不要判断是不是nil，用len=0判断兼容性更好

2021-07-01 09:44 UTC, breezelxp commented on src/scene_server/topo_server/core/settemplate/sync_status.go
> +	setModules := make(map[int64][]metadata.ModuleInst, modulesInstResult.Data.Count)
这个长度不对

2021-07-01 09:44 UTC, breezelxp commented on src/scene_server/topo_server/core/settemplate/sync_status.go
> +	taskFilter := mapstr.MapStr{
这个不能叫filter, 应该是fields,而且也不能这么传，应该只传要的字段信息就可以了

2021-07-01 09:44 UTC, breezelxp commented on src/scene_server/topo_server/service/set_template.go
> +	ctx.RespEntityWithError(s.Core.SetTemplateOperation().GetLatestSyncTaskDetail(ctx.Kit, option.SetIDs, filter))
把这个判断挪出来
s.Core.SetTemplateOperation().GetLatestSyncTaskDetail(ctx.Kit, option.SetIDs, filter)，不要嵌套到里边

2021-07-01 11:24 UTC, breezelxp commented on src/scene_server/topo_server/service/set_template.go
> +		ctx.RespAutoError(err)
return ?

2021-07-01 13:06 UTC, merged