模型实例事件watch支持按模型订阅功能
Tencent/bk-cmdb pull request #5417
Opened 2021-06-29 13:06 UTC by wcy00000000000000

### 新加的功能:
- 模型实例事件watch支持按模型订阅功能
- 添加主线模型实例事件监听

2021-07-05 12:29 UTC, wcy00000000000000 commented on src/ac/iam/gen_id.go
> +	}
这个是要支持的，是其它那些不用关联权限资源的操作的返回值

2021-07-05 12:35 UTC, wcy00000000000000 commented on src/ac/parser/event.go
> +				model, err := ps.getOneModel(mapstr.MapStr{common.BKObjIDField: subResource.String()})
直接传身份ID的话在下面事件监听的时候还是需要转成bk_obj_id的（实例里只能拿到这个值）

2021-07-06 09:22 UTC, breezelxp requested changes

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/client.go
> +	cursor      string
startCursor ?

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/client.go
> +		opts.id = node.ID
这个用法看起来不太规范，传参，除非是初始化等场景，一般不在入参后再调整数据，最好是只读

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/client.go
> +		opts.id = node.ID
看了下你的调用，可以把这个当个独立的参数传入，是不是更合理？

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/watch.go
> +func (c *Client) isNodeWithSubResource(node *watch.ChainNode, subResource string) bool {
这个函数的实现不够严谨，有没有subresourceu首先和资源类型有关系，host，set这些应该是没有的。而且这个要在请求进入的时候就要严格校验

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/watch.go
> +func (c *Client) isNodeWithSubResource(node *watch.ChainNode, subResource string) bool {
补充注释

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/watch.go
> +		return true
严格上来讲，这个返回true是不合适的，和语义不相符

2021-07-06 09:22 UTC, breezelxp commented on src/source_controller/cacheservice/event/watch/watch.go
> +		return true
看了下调用，很多逻辑不适配这个，比如：
![image](https://user-images.githubusercontent.com/26254420/124575700-30befa80-de7e-11eb-8a5d-07ef3758650b.png)

2021-07-06 09:23 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/watch/client.go
> +		if key.Collection() == common.BKTableNameBaseInst || key.Collection() == common.BKTableNameMainlineInstance {
key.Collection()是虚拟collection，分表不影响的

2021-07-06 09:26 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/watch/watch.go
> +		return true
这个是参考isNodeWithEventType写的，我加个注释还是改个名字？

2021-07-06 09:32 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/watch/client.go
> +		if key.Collection() == common.BKTableNameBaseInst || key.Collection() == common.BKTableNameMainlineInstance {
加一个VirtualCollection()函数可以不？

2021-07-08 09:23 UTC, breezelxp requested changes

2021-07-08 09:23 UTC, breezelxp commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		if _, exists := f.mainlineObjectMap[objID]; exists {
加锁

2021-07-09 06:51 UTC, wcy00000000000000 commented on src/scene_server/admin_server/service/migrate.go
> +				Name: "index_sub_resource", Keys: map[string]int32{common.BKSubResourceField: 1}, Background: true,
刚刚发现bk_resource决定的是表名，不能跟它建复合索引

2021-07-09 07:22 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		rid = rid + ":" + chainNodes[0].Oid
不会空指针异常，因为有冲突所以一定是有至少一个的

2021-07-19 06:43 UTC, breezelxp approved these changes

2021-07-19 06:44 UTC, merged