定时检查zk节点注册情况并保证节点注册正常
Tencent/bk-cmdb pull request #5433
Opened 2021-07-01 13:44 UTC by fireyun

### 优化的功能:
- 定时检查zk节点注册情况并保证节点注册正常

2021-07-06 09:58 UTC, breezelxp requested changes

2021-07-06 09:58 UTC, breezelxp commented on src/common/registerdiscover/zkregdiscv.go
> +func (zkRD *ZkRegDiscv) loopRegisterNode(path string, data []byte) {
这个设计有问题，如果调RegisterAndWatch两次，这个临时变量就会有问题，引发一系列其它问题

2021-07-06 12:47 UTC, fireyun commented on src/common/registerdiscover/zkregdiscv.go
> +func (zkRD *ZkRegDiscv) loopRegisterNode(path string, data []byte) {
已支持调用多次

2021-07-08 03:37 UTC, wcy00000000000000 commented on src/common/registerdiscover/zkregdiscv.go
> +	registeredPathsMap sync.Map
这个感觉没啥用，不会有注册多个的场景吧

2021-07-08 07:02 UTC, fireyun commented on src/common/registerdiscover/zkregdiscv.go
> +	registeredPathsMap sync.Map
RegisterAndWatch作为公共方法，除了用来注册监听服务节点，还可注册监听其他路径，用作其他需求，这个用来保存多个注册路径

2021-07-08 09:44 UTC, breezelxp commented on src/common/registerdiscover/zkregdiscv.go
> +			zkRD.registeredPathsMap.Store(registerPath, struct{}{})
loop逻辑这里为什么只有store, 没有delete？

2021-07-08 09:44 UTC, breezelxp commented on src/common/registerdiscover/zkregdiscv.go
> +		registerPath := pathMgr.getRegisterPath()
registerPath 如果为""呢？

2021-07-08 13:36 UTC, breezelxp approved these changes

2021-07-08 13:36 UTC, merged