为各个子服务模块新增version接口
Tencent/bk-cmdb pull request #5449
Opened 2021-07-07 09:58 UTC by fireyun

### 新加的功能:
- 为各个子服务模块新增version接口

close issue #5448

2021-07-08 03:27 UTC, breezelxp requested changes

2021-07-08 03:27 UTC, breezelxp commented on src/apiserver/service/healthz.go
> +func (s *service) Healthz(req *restful.Request, resp *restful.Response) {
version的接口，也是要按healthz的方式去处理，为什么现在都分开去处理？每个组件都要写一次，加一个公共路由不就可以了？

2021-07-08 06:49 UTC, fireyun commented on src/apiserver/service/healthz.go
> +func (s *service) Healthz(req *restful.Request, resp *restful.Response) {
已调整

2021-07-19 05:57 UTC, breezelxp approved these changes

2021-07-19 05:57 UTC, merged