feature 转移主机到另一个业务下添加业务校验 限制主机转移至归档业务
Tencent/bk-cmdb pull request #5463
Opened 2021-07-09 06:06 UTC by chalice-1831

### 修复的问题：
- 限制主机转移至归档业务

issue #5461

2021-07-09 08:07 UTC, breezelxp requested changes

2021-07-09 08:07 UTC, breezelxp commented on src/source_controller/coreservice/core/host/transfer/transfer.go
> +func (t *genericTransfer) validAppStatus(kit *rest.Kit) (bool, errors.CCErrorCoder) {
直接封装一个业务是否已经归档的函数，用filter条件去命中，直接count，效率更高

2021-07-09 11:30 UTC, fireyun commented on src/common/errInfo.go
> +	CCErrTransferHostToApp        = 1110031
名字改下，应该为CCErrTransferHostToArchivedApp

2021-07-09 11:30 UTC, fireyun commented on src/source_controller/coreservice/core/host/transfer/manager.go
> +	if !isAppArchived {
下面加一行错误日志

2021-07-09 11:30 UTC, fireyun commented on src/source_controller/coreservice/core/host/transfer/transfer.go
> +	appCond.Field(common.BKDataStatusField).Eq("disabled")
条件直接用map，省去类型的来回转换

2021-07-16 03:53 UTC, breezelxp requested changes

2021-07-16 03:53 UTC, breezelxp commented on src/source_controller/coreservice/core/host/transfer/manager.go
> +
这个判断逻辑是不是反了？
顺便把validAppArchivedStatus函数名调整为isAppArchived是不是更合适？

2021-07-16 07:28 UTC, breezelxp approved these changes

2021-07-16 07:28 UTC, merged