feature 优化toposerver中operation/association相关结构与代码逻辑
Tencent/bk-cmdb pull request #5500
Opened 2021-07-19 10:12 UTC by chalice-1831

### 新加的功能:
- 通过bk_obj_id进行批量查询模型关联关系
### 优化的功能:
- toposerver中operation/association相关结构与代码优化

issue #5450 

新增接口
### 功能描述

通过模型id批量查询模型关联关系

### 接口地址

{{ common_args_desc }}

### 请求参数

接口参数

| 参数      | 类型  | 必选 | 描述                         |
| --------- | ----- | ---- | ---------------------------- |
| bk_obj_id | array | 是   | 用于查询的模型id，可以查多个 |

### 请求参数示例

```json
{
    "bk_obj_id": [
        "bk_router",
        "bk_switch"
    ]
}
```

### 返回结果示例

```json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "success",
    "permission": null,
    "data": [
        {
            "id": 5,
            "bk_supplier_account": "0",
            "bk_obj_asst_id": "bk_switch_connect_host",
            "bk_obj_asst_name": "",
            "bk_obj_id": "bk_switch",
            "bk_asst_obj_id": "host",
            "bk_asst_id": "connect",
            "mapping": "1:n",
            "on_delete": "none",
            "ispre": false
        },
        {
            "id": 7,
            "bk_supplier_account": "0",
            "bk_obj_asst_id": "bk_switch_belong_bk_router",
            "bk_obj_asst_name": "aaaa",
            "bk_obj_id": "bk_switch",
            "bk_asst_obj_id": "bk_router",
            "bk_asst_id": "belong",
            "mapping": "n:n",
            "on_delete": "none",
            "ispre": null
        }
    ]
}
```

### 返回结果参数说明

#### data

| 字段 | 类型  | 描述                     |
| ---- | ----- | ------------------------ |
| data | array | 查到的模型关联关系的数组 |

2021-07-20 12:30 UTC, wcy00000000000000 requested changes

2021-07-20 12:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +func (assoc *association) DeleteAssociation(kit *rest.Kit, cond mapstr.MapStr) error {
去掉这个函数，这个不需要被使用，只需要DeleteAssociationWithPreCheck就可以了。然后DeleteAssociationWithPreCheck调这个函数又查了一次模型关联做校验，这个pre判断需要在DeleteAssociationWithPreCheck里加

2021-07-20 12:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +	// all the pre check has finished, delete the association now.
需要确定下on_delete是否需要支持

2021-07-20 12:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +func (assoc *association) isObjectInAssocValid(kit *rest.Kit, objectID, asstObjectID string) error {
可以用in这两个模型ID的方式一次性查出来

2021-07-22 02:52 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5500) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5500) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-cmdb?pullRequest=5500) it.</sub>

2021-07-22 08:46 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5500) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5500) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-cmdb?pullRequest=5500) it.</sub>

2021-08-20 03:34 UTC, wcy00000000000000 requested changes

2021-08-20 03:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +func (assoc *association) SearchObjectAssociation(kit *rest.Kit,
合了api machinery之后可以删掉

2021-08-20 03:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +	}
是不是可以用count？

2021-08-20 03:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +	}
是否可以用count？

2021-08-20 03:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +	err := data.MarshalJSONInto(asst)
data是不是可以在外层解析http请求的DecodeInto里直接解成metadata.Association类型？

2021-08-20 03:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/association.go
> +func (assoc *association) isObjectInAssocValid(kit *rest.Kit, objectID, asstObjectID string) error {
这里如果改成用for循环判断出来哪个不存在是否更容易理解一点？

2021-08-30 07:31 UTC, breezelxp approved these changes
LGTM

2021-08-30 07:33 UTC, merged