批量获取topo节点主机/服务实例数量
Tencent/bk-cmdb pull request #5503
Opened 2021-07-20 03:20 UTC by laodiu

### 新加的功能:
- 批量获取topo节点主机、服务实例数量，支持自定义topo节点的获取。
### 修复问题
- 随着单个业务下的集群模块数量越多，接口/find/topoinst_with_statistics/biz/{bk_biz_id}查询处理数据量会越大，且需要统计topo节点主机、服务实例数量，响应时间过长，接口性能下降。将该接口中的统计节点主机、服务实例数量拆分出来，单独通过新增接口异步获取

issues  #5468

2021-07-22 14:46 UTC, breezelxp requested changes

2021-07-22 14:46 UTC, breezelxp commented on src/common/definitions.go
> +	BKParamMaxLength = 1000
注释

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +	}
函数名和数据结构的定义名都太长了，另外，行长都超过120行了。

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +	resp, err := s.searchBusinessTopoNodeHostAndServiceInstancesCount(ctx)
把这个函数的实现直接合并到这里。

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +		blog.Errorf("[api-asst] failed to parse the path params id(%s), error info is %s , rid: %s", ctx.Request.PathParameter("app_id"), err.Error(), ctx.Kit.Rid)
这个日志是从那儿拷由过来的？

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +	if len(input.Condition) > common.BKParamMaxLength {
这个前端超了，就直接挂了么？前端怎么处理的，会分页么？

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +		}
这么多分支，用switch

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			topoNodeServiceInstCount.ServiceInstanceCount = moduleServiceInstanceCount[topoNodeServiceInstCount.InstID]
这段实现不行，有的模块下有十几w主机，现在的实现，这种场景处理不了。

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			serviceInstanceCount += moduleServiceInstanceCount[moduleID]
服务实例的，是服务实例的，跟这个主机关系没有关系，不能用这个计数。

2021-07-22 14:46 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +		}
整体代码在规范程度上，有几个需要注意：
1. 变量与函数名不要太长，像listSetRelationOption，这样就略长，是个局部变量，很容易看出来是做什么的，opts就足够了。
2. 换行要注意，单行不能超过120，配置下IDE。
3. 日志要打规范
4. 逻辑上关系比较弱的，可以适当换空行，增强代码可读性。

2021-07-23 02:24 UTC, laodiu commented on src/scene_server/topo_server/service/association.go
> +	if len(input.Condition) > common.BKParamMaxLength {
前端会分页进行请求，入参长度超过了限制的最大长度，返回提示，终止本次请求

2021-07-23 02:26 UTC, laodiu commented on src/scene_server/topo_server/service/association.go
> +	if len(input.Condition) > common.BKParamMaxLength {
或者如果参数个数超过了最大限制、就按最大长度截取参数进行查询，然后返回结果？

2021-07-23 03:40 UTC, laodiu commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			serviceInstanceCount += moduleServiceInstanceCount[moduleID]
服务实例数量按bizID查询出来后，按照module_id进行统计、自定义topo层级服务实例的统计逻辑如下：
1、通过自定义层级objID获取对应setArr
2、通过setArr查询ModuleHostConfig，可以统计出setArr包含哪些module_id,即可以统计出该自定义层级下有多少module_id
3、通过自定义层级下的module_id去获取服务实例

2021-07-26 08:22 UTC, laodiu commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			topoNodeServiceInstCount.ServiceInstanceCount = moduleServiceInstanceCount[topoNodeServiceInstCount.InstID]
通过GetDistinctCount方法、只获取主机的数量，提高查询效率

2021-07-26 08:23 UTC, laodiu commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			serviceInstanceCount += moduleServiceInstanceCount[moduleID]
主机数量的获取、主要通过 GetDistinctCount函数去获取，不再与服务实例有关联

2021-07-27 07:49 UTC, breezelxp requested changes

2021-07-27 07:49 UTC, breezelxp commented on src/source_controller/coreservice/core/common/common.go
> +func (c *commonOperation) GetDistinctCount(kit *rest.Kit, option *metadata.DistinctFieldOption) ([]interface{},
这个实现有问题吧？count就是count怎么又把详情全返回了，那直接用原来的接口就可以了，为什么要再封装一个？

2021-07-27 07:57 UTC, breezelxp requested changes

2021-07-27 07:57 UTC, breezelxp commented on src/common/definitions.go
> +	BKParamMaxLength = 1000
把这个常量定义去了吧，不会有其它场景能用到，直接在代码使用的附近const一下使用即可

2021-07-27 07:57 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +	}
这种实现不行，一次查了一个业务下所有的服务实例，这可能是几十w，一次怎么能拉这么多数据。

2021-07-27 07:57 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +	resp, _ := assoc.clientSet.CoreService().Instance().ReadInstance(kit.Ctx, kit.Header, common.BKInnerObjIDModule,
这个为什么有异常不处理？

2021-07-29 02:45 UTC, breezelxp requested changes

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			}
异常的要处理，不然回去的，全是0啦

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +	pipeline := make(chan bool, 10)
并发10偏大，调到10吧

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			}
其它类似的写法，都一并处理下哈

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +	}
这个判断有2个问题：
1. 返回的e也是个nil， 导致返回的是nil，nil, 上层逻辑会因此崩了，不太符合err的使用惯例。
2. 为什么要这个判断，这个没有严格说服务实例的量已经要>=set的量吧？如果set下没有模块呢？

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +			}
这个判断再考虑下？其它类似的也在看下

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +	return results, nil
这个返回是有问题的，其它类似的写法也调整下

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +		filters = append(filters, filter)
filters = append(filters, mapstr.Mapstr{objID: instID})
这样写是不是更简洁？
其它类似的也可以调整一下

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +func (assoc *association) getSvcInstCountBySetIDs(kit *rest.Kit, objID string, instIDs [][]int64) ([]int64, error) {
这个函数是不是和上边的重复了？

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +			"rid: %s", ctx.Request.PathParameter("app_id"), err.Error(), ctx.Kit.Rid)
ctx.Request.PathParameter("app_id") ？

2021-07-29 02:45 UTC, breezelxp commented on src/scene_server/topo_server/service/association.go
> +			"rid: %s", ctx.Request.PathParameter("app_id"), err.Error(), ctx.Kit.Rid)
之前说过不要在error里这么写GetTopoNodeHostAndSerInstCount。比如这个报错可以这么写：
blog.Errorf("parse biz id: %s from url path, err: %v, rid: %s", ctx.Request.PathParameter("bk_biz_id"), err, kit.Rid)

2021-07-29 06:29 UTC, breezelxp requested changes

2021-07-29 06:29 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +	"configcenter/src/common/mapstr"
顺序？

2021-07-29 06:29 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
>  	wg.Wait()
上面协程并发都已经有firstError了，是不是在这里就可以退出了？不用再继续执行逻辑了？
其它类似的也一并处理了。

2021-07-29 06:29 UTC, breezelxp commented on src/scene_server/topo_server/core/operation/association_mainline_inst.go
> +				}
这里可以减化写，即然目的是为了判断并发里有没有err，也没有额外的处理，那直接进行赋值操作即可：
firstErr = kit.CCError.CCError(common.CCErrCommDBSelectFailed)
其它类似的也一并处理了。

2021-07-29 06:57 UTC, breezelxp approved these changes

2021-07-29 07:07 UTC, merged