feature 优化toposerver中inst/association相关结构与代码
Tencent/bk-cmdb pull request #5505
Opened 2021-07-20 09:37 UTC by chalice-1831

### 优化的功能:
- 优化toposerver中inst/association相关结构与代码

issue #5450

2021-07-20 13:16 UTC, wcy00000000000000 requested changes

2021-07-20 13:16 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +	curData.Set("name", objectAsst.AssociationAliasName)
这个没有被用到

2021-07-20 13:16 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +	auditLog, err := audit.GenerateAuditLog(generateAuditParameter, instanceAssociationID, objID, nil)
可以把ID赋值给用来创建的那个实例关联数据，然后填到生成审计的详情参数里

2021-07-20 13:16 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +	}
先获得全部的obj->instIDs的map，然后批量查，批量删

2021-07-21 12:15 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/inst/association.go
> +	}
按照这个方式修改后整体代码和CheckAssociations相同了，可以把这个函数删除，调用到的地方全都替换成CheckAssociations

2021-07-21 12:33 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +	}
可以，原本这2个实现不太一样，现在可以只用一个

2021-08-30 14:08 UTC, wcy00000000000000 requested changes

2021-08-30 14:08 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +	}
这一段感觉没有用，可以去掉，不管删除的实例关联对应的模型关联有没有都需要删掉

2021-08-30 14:08 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +		if len(asstInstRsp.Info) > 0 {
这个只需要判断是否存在，可以用count替换

2021-09-01 06:44 UTC, breezelxp approved these changes
LGTM

2021-09-01 06:44 UTC, merged