feature 优化toposerver中operation/graphics相关结构与代码逻辑
Tencent/bk-cmdb pull request #5510
Opened 2021-07-23 03:00 UTC by linfang-canway

### 新加的功能:
- xxxx
### 优化的功能:
- 优化toposerver中operation/graphics相关结构与代码逻辑
### 修复的问题：
- xxxx

2021-07-29 02:40 UTC, wcy00000000000000 requested changes

2021-07-29 02:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/graphics.go
> +	if nil != err {
日志

2021-07-29 02:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/graphics.go
> +func (g *graphics) findObject(kit *rest.Kit, cond mapstr.MapStr) ([]metadata.Object, error) {
下面的这些工具函数后续可以用对应的依赖函数替换

2021-07-29 02:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/graphics.go
> +			node.SetSupplierAccount("0")
确认一下这个是否需要用object的SupplierAccount还是直接用0

2021-07-29 02:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/graphics.go
> +				}
这里可以批量查

2021-07-29 02:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/graphics.go
> +			objAssts[asst.ObjectID] = append(objAssts[asst.ObjectID], asst)
这里是否需要区分supplier account？

2021-07-29 03:09 UTC, linfang-canway commented on src/scene_server/topo_server/logics/operation/graphics.go
> +			node.SetSupplierAccount("0")
node.SetSupplierAccount(kit.SupplierAccount) ？

2021-07-29 09:36 UTC, linfang-canway commented on src/scene_server/topo_server/logics/operation/graphics.go
> +			objAssts[asst.ObjectID] = append(objAssts[asst.ObjectID], asst)
这里找不到区分SupplierAccount的条件，只有kit中有SupplierAccount参数

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +		}
封装成方法

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +func (g *graphics) SelectObjectTopoGraphics(kit *rest.Kit, scopeType, scopeID string) ([]metadata.TopoGraphics, error) {
单个方法过长，单个方法或函数尽量控制在80行内

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +	if scopeType == "global" {
使用短路逻辑，利用逆向思维，判断!="global"直接提前返回，可减少层级嵌套和提高可读性

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +		}
封装成方法

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +		}
封装成方法

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +	}
两块逻辑是连在一起的，不需要空格

2021-07-30 06:40 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/graphics.go
> +	}
两块逻辑是连在一起的，不需要空格

2021-08-31 07:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/graphics.go
> +	}
获取asstKindIDs的这一步可以挪到上面遍历assts.Info的时候一起做

2021-09-01 02:06 UTC, breezelxp approved these changes
LGTM

2021-09-01 02:07 UTC, merged