feature 优化toposerver中operation/import_association相关结构与代码逻辑
Tencent/bk-cmdb pull request #5522
Opened 2021-07-29 01:59 UTC by chalice-1831

### 优化的功能:
- 优化toposerver中operation/import_association相关结构与代码逻辑

issue #5450

2021-07-30 03:47 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/import_association.go
> +func NewImportAssociation(cli *association, kit *rest.Kit, objID string, importData map[int]metadata.ExcelAssociation,
导出的函数缺注释

2021-07-30 03:47 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/import_association.go
> +		}
封装成方法

2021-07-30 03:47 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/import_association.go
> +		}
封装成方法

2021-07-30 03:47 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/import_association.go
> +func (ia *importAssociation) importAssociation() {
单个方法过长，尽量不要超过80行

2021-07-30 03:47 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/import_association.go
> +		return false, err
增加错误日志

2021-07-30 03:47 UTC, fireyun commented on src/scene_server/topo_server/logics/operation/import_association.go
> +		return 0, fmt.Errorf(ia.language.Languagef("import_instance_not_found", objID, primary))
返回错误前，增加错误日志，其他没加错误日志的地方都加下

2021-08-19 06:57 UTC, wcy00000000000000 requested changes

2021-08-19 06:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/import_association.go
> +		return ia.kit.CCError.Error(common.CCErrCommHTTPDoRequestFailed)
```suggestion
		return err
```

2021-08-19 06:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/operation/import_association.go
> +			ia.parseInstToImportAssociationObjectInst(objID, instIDKey, inst)
和parseInstToImportObjectInst逻辑相同，可以合并

2021-09-08 08:04 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/operation/import_association.go
> +		}
AuthorizeByInstances是被AuthorizeByInstanceID调用的，前面还有校验逻辑，这里不能替换吧

2021-09-08 08:20 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/operation/import_association.go
> +func (ia *importAssociation) getTargetIndexSrcDstInstID(idx int, asst *metadata.Association,
src和dst因为objid和asstobjid的关系调用的函数不同，合成一个方式是不是会有些表意不明

2021-09-10 06:31 UTC, breezelxp approved these changes

2021-09-10 06:31 UTC, merged