feature 优化toposerver中inst相关结构与代码逻辑
Tencent/bk-cmdb pull request #5523
Opened 2021-07-29 02:00 UTC by chalice-1831

### 优化的功能:
- 优化toposerver中inst相关结构与代码逻辑

issue #5450

2021-08-17 12:13 UTC, wcy00000000000000 requested changes

2021-08-25 11:41 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/inst/inst.go
> +func (c *commonInst) CreateInstBatch(kit *rest.Kit, obj metadata.Object,
update也是单次更新一个，CreateManyInstance不方便使用，这里是根据每个index的顺序进行更新或者创建，每一个报错都会进行排列，批量的话就需要先区别这个实例是否是更新还是创建，然后再分开成两个部分进行更新和创建，而且创建和更新的入参和返回参数与这个不服，个人感觉不太好在不修改返回结构的前提上进行调整，这个逻辑是用于导入excel的逻辑，对每个错误的定位有要求

2021-09-01 13:08 UTC, wcy00000000000000 requested changes

2021-09-03 08:25 UTC, wcy00000000000000 requested changes

2021-09-03 08:25 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +		instIDs := []int64{}
用make初始化

2021-09-03 08:25 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +			item.Set("asso_id", relation[id])
返回值可以带上relation，在外层就可以直接用instID解了

2021-09-03 08:25 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +		return nil, kit.CCError.CCError(common.CCErrTopoModuleSelectFailed)
不需要报错，直接返回空数组即可

2021-09-03 08:25 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +			Condition: mapstr.MapStr{objPair.Object.GetInstIDFieldName(): mapstr.MapStr{common.BKDBIN: instIDs}},
可以加个fields

2021-09-03 08:25 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +		return false, kit.CCError.CCErrorf(common.CCErrCommParamsIsInvalid, common.BKModuleIDField)
返回false就行，不用报错

2021-09-07 07:30 UTC, wcy00000000000000 requested changes

2021-09-07 07:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +		Condition: map[string]interface{}{metadata.GetInstIDFieldByObjID(obj.ObjectID): instID},
```suggestion
		Condition: map[string]interface{}{instIDField: instID},
```

2021-09-07 07:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/inst.go
> +	}
这一段可以用count代替

2021-09-07 07:34 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/inst/inst.go
> +		colInput.Set(common.BKObjIDField, objID)
coreservice会设置一次supplier account

2021-09-07 11:45 UTC, breezelxp approved these changes

2021-09-07 11:45 UTC, merged