feature 优化toposerver中model/mainline_association相关结构与代码逻辑
Tencent/bk-cmdb pull request #5524
Opened 2021-07-29 02:01 UTC by chalice-1831

### 优化的功能:
- 优化toposerver中model/mainline_association相关结构与代码逻辑

issue #5450

2021-07-30 04:00 UTC, wcy00000000000000 requested changes

2021-07-30 04:00 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +func (assoc *association) DeleteAssociation(kit *rest.Kit, cond mapstr.MapStr) error {
这个不可以用DeleteAssociationWithPreCheck替换，因为它校验了不能删除主线关联，这个也不应该大写，应该作为仅给主线关联删除用的一个私有的工具函数

2021-08-03 12:04 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +	// generate audit log.
创建模型的方法有审计了

2021-08-17 13:17 UTC, wcy00000000000000 requested changes

2021-08-17 13:17 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +func (assoc *association) getMainlineNodeObject(kit *rest.Kit,
去掉

2021-08-17 13:17 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +func (assoc *association) deleteAssociation(kit *rest.Kit, cond mapstr.MapStr) error {
确认一下是否是一个定制的函数只有删主线模型用到，如果是的话可以把1196行以下的和上面的函数合到一起

2021-09-02 14:32 UTC, wcy00000000000000 requested changes

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +			"err: %v, rid: %s", childObjID, parentObjID, err, kit.Rid)
这段日志和实际操作不符

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +	parentObjID string) error {
这个不超长，不用换行

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +	// create audit log for the created instances.
考虑一下这段加审计的逻辑是否要放到SetMainlineInstAssociation里

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +		return fmt.Errorf("mainline object(%s) has no parent or child", targetObjID)
同上，最好不要用fmt生成error

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +	if rsp.Info[0].IsPre != nil && *rsp.Info[0].IsPre {
这个判断可以提到前面遍历rsp.Info的时候做，对每一个都要判断

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +
是不是缺了重置模型关联的步骤？

2021-09-02 14:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +	// object的删除函数通过object的id进行删除，需要在这里查一次object的id
可以把DeleteObject改成mapstr格式的入参（可以少查一次），然后如果有多个用id删的话可以封一个DeleteObjectByID的函数

2021-09-03 07:43 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +
函数名改了 原函数SetMainlineParentObject实际调用了createMainlineObjectAssociation，我就改用后面的了

2021-09-09 04:05 UTC, wcy00000000000000 requested changes

2021-09-09 04:05 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +func (assoc *association) SearchMainlineAssociationTopo(kit *rest.Kit,
换行位置错误

2021-09-09 04:05 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/mainline_association.go
> +	needFind := []string{targetObjID}
这个挪到下面那个循环前面定义

2021-09-09 08:42 UTC, wcy00000000000000 requested changes

2021-09-09 08:42 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +	resp, err := s.Logics.AssociationOperation().SearchMainlineAssociationTopo(ctx.Kit, bizObj.ObjectID)
bizObj.ObjectID其实就是ctx.Request.PathParameter("bk_obj_id")，不用查一次

2021-09-09 08:42 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	if err := validUpdateModuleData(kit, data, moduleInstance.Data); err != nil {
这里可以传moduleInstance.Data.Info[0]，这样validUpdateModuleData函数就不用每次去取了

2021-09-09 10:01 UTC, breezelxp approved these changes

2021-09-09 11:36 UTC, merged