feature 优化toposerver中inst/mainline_association相关结构与代码逻辑
Tencent/bk-cmdb pull request #5525
Opened 2021-07-29 02:02 UTC by chalice-1831

### 优化的功能:
- 优化toposerver中inst/mainline_association相关结构与代码逻辑

issue #5450

2021-08-02 14:01 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +func (assoc *association) SetMainlineParentInst(kit *rest.Kit, childInst mapstr.MapStr, instID int64) error {
可以改成批量更新的

2021-08-02 14:05 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +func (assoc *association) DeleteMainlineInstWithID(kit *rest.Kit, obj *metadata.Object, instID int64) error {
可以改成批量的

2021-08-04 03:31 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +	if canReset, repeatedInstName, err = assoc.checkInstNameRepeat(kit, current, currentInsts.Info); err != nil {
bk_inst_name没有唯一索引吧

2021-08-04 09:21 UTC, chalice-1831 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +func (assoc *association) getMainlineInst(kit *rest.Kit, obj *metadata.Object, inst mapstr.MapStr,
可以改成批量查询，删掉的话调用到的函数改成批量查询会使函数变得很长

2021-09-03 10:02 UTC, wcy00000000000000 requested changes

2021-09-03 10:02 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +		expectParent2Children[parentID] = append(expectParent2Children[parentID], childID)
这个不对，expectParent2Children的parent应该是新创建的对应inst，应该在前面先生成parentID->currentID的map然后这里用

2021-09-08 08:49 UTC, wcy00000000000000 requested changes

2021-09-08 08:49 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +	}
换成CheckAssociation

2021-09-08 08:49 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +			blog.Errorf("get inst id in current insts failed, err: %v, rid: %s", err, kit.Rid)
可以打一下哪个inst id解析失败了，下同

2021-09-08 13:38 UTC, wcy00000000000000 requested changes

2021-09-08 13:38 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +		childInstID, err := child.Int64(common.GetInstIDField(currentObjID))
```suggestion
		childInstID, err := child.Int64(common.GetInstIDField(childObjID))
```

2021-09-08 13:38 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +		blog.Errorf("check object(%s) insts(%v) associations failed, err: %v, rid: %s", objID, instID, err, kit.Rid)
漏了个return err

2021-09-08 13:38 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/mainline_association.go
> +func (assoc *association) SearchMainlineAssociationInstTopo(kit *rest.Kit, objID string, instID int64,
拆分方式可以换一种，for objectID := objID; len(objectID) != 0; objectID = mainlineObjectChildMap[objectID] {这个循环里面的内容可以拆出一个函数，然后for _, instance := range instanceRsp.Info {这个里面的也拆出来一个

2021-09-08 14:13 UTC, breezelxp approved these changes

2021-09-08 14:32 UTC, merged