feature 优化toposerver中inst/business相关结构与代码逻辑
Tencent/bk-cmdb pull request #5532
Opened 2021-07-30 06:54 UTC by linfang-canway

### 新加的功能:
- xxxx
### 优化的功能:
- 优化toposerver中inst/business相关结构与代码逻辑
### 修复的问题：
- xxxx

2021-08-02 10:08 UTC, wcy00000000000000 requested changes

2021-08-02 10:08 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +func (b *business) findBusiness(kit *rest.Kit, cond *metadata.QueryBusinessRequest) (count int,
这个函数的实现和FindBiz一样，直接用FindBiz替换吧

2021-08-02 10:08 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +		}
这里只用到了BizName，可以直接用util.GetStrByInterface取

2021-08-02 10:08 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +		if !NumRegex.MatchString(numPart) {
NumRegex这个不用大写

2021-09-02 13:04 UTC, wcy00000000000000 requested changes

2021-09-02 13:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +	// count hosts
这个原本没有的逻辑为什么要加？

2021-09-02 13:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
>  	if errKey, err := page.Validate(true); err != nil {
这个函数里生成的page不需要校验吧

2021-09-02 13:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
这个函数调的还是core的，要在logics里实现然后调用

2021-09-03 06:54 UTC, linfang-canway commented on src/scene_server/topo_server/service/inst_business.go
> +	// count hosts
这段逻辑一直都存在啊

2021-09-10 12:26 UTC, wcy00000000000000 requested changes

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +	var business *mapstr.MapStr
```suggestion
	var business mapstr.MapStr
```

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +				blog.ErrorJSON("get biz id failed, err: %v, biz: %s, rid: %s", err, business, ctx.Kit.Rid)
```suggestion
				blog.Errorf("get biz id failed, err: %v, biz: %#v, rid: %s", err, business, ctx.Kit.Rid)
```

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +	data := make(mapstr.MapStr, 0)
map的make不需要加长度，下面的也改下
```suggestion
	data := make(mapstr.MapStr)
```

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +		blog.Errorf(" find objects failed, err: %v, rid: %s", ctx.Request.PathParameter("obj_id"), err,
```suggestion
		blog.Errorf("find object %s failed, err: %v, rid: %s", ctx.Request.PathParameter("obj_id"), err,
```

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +	attrArr, err := s.Core.AttributeOperation().FindBusinessAttribute(ctx.Kit, attrCond.ToMapStr())
这个为什么要改？原本那个才是对的

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business.go
> +			blog.Errorf("SearchBusiness failed, list authorized resources failed, user: %s, err: %v, rid: %s",
这种函数名的日志处理一下，不要这样用，然后如果第一句描述整个函数，后面才是当前操作的要去掉第一句
```suggestion
			blog.Errorf("list authorized resources failed, user: %s, err: %v, rid: %s",
```

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +	module ModuleOperationInterface, set SetOperationInterface) {
不超长度，不用换行

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +	}
为什么要重新生成一个？直接用cond去查就行，而且cond里可以带disableCounter，这样函数就不需要disableCounter参数了

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +		blog.Errorf("create business failed, err: %v, data: %#v, rid: %s", err, data, kit.Rid)
日志不要笼统的写创建业务失败，写详细一点，比如这个操作实际是create association for new default biz of different supplier account，下面的也要按实际操作打日志

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +		return 0, fmt.Errorf("src[%s] model and dest[%s] model should be neighbour in the mainline topology",
用kit.CCErr生成error，尽量不要用fmt.Errorf，别的这样用的地方也检查下

2021-09-10 12:26 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +func (b *business) createSet(kit *rest.Kit, obj metadata.Object, data mapstr.MapStr) (*metadata.CreateOneDataResult,
去掉

2021-09-13 03:30 UTC, wcy00000000000000 requested changes

2021-09-13 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +		},
直接用 common.BKAppIDField: bizID 即可

2021-09-13 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/business.go
> +	rsp, err := b.clientSet.CoreService().Count().GetCountByFilter(kit.Ctx, kit.Header, common.BKTableNameBaseApp,
```suggestion
	rsp, err := b.clientSet.CoreService().Count().GetCountByFilter(kit.Ctx, kit.Header, common.BKTableNameModuleHostConfig,
```

2021-09-13 03:37 UTC, wcy00000000000000 requested changes
src/scene_server/topo_server/service/inst_business.go文件里的GetInternalModule这个接口挪到src/scene_server/topo_server/service/inst_module.go里，改成用Logics里的GetInternalModule

2021-09-13 06:58 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/business.go
> +	if err := b.createAssociationByNewSupplier(kit, data); err != nil {
去掉这段逻辑及相关函数，现在这种方式不是一个完整的闭环管理逻辑。后续如有相关形态支持，再统一考虑。

2021-09-13 08:00 UTC, merged