优化toposerver中model/attribute相关结构和代码逻辑
Tencent/bk-cmdb pull request #5533
Opened 2021-07-30 08:50 UTC by laodiu

### 优化的功能:
- 优化toposerver中model/attribute相关结构与代码逻辑

issue #5450

2021-08-02 08:55 UTC, wcy00000000000000 requested changes

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
原本的逻辑会对IsOnly和PropertyGroup做特殊处理，这里漏了

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	rsp, err := a.clientSet.CoreService().Model().CreateModelAttrs(kit.Ctx, kit.Header, attr.ObjectID, &input)
创建前漏了校验步骤，创建后漏了对返回值的判断

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		rsp, err := a.clientSet.CoreService().Model().DeleteModelAttr(kit.Ctx, kit.Header, attrItem.ObjectID, &metadata.DeleteOption{Condition: cond})
如果这个cond对应了多个属性的话，这里循环删是有问题的，应该按objectID聚合一下然后批量删（确认一下是否允许一次删多个不同模型的属性），审计可以先全部生成之后再批量加

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		blog.Warnf("add object attribute, but not allow to add required attribute to mainline object: %+v. rid: %d.", data, kit.Rid)
长度超了，换一下行，别的长度过长的也要处理一下

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +func (a *attribute) isMainlineModel(kit *rest.Kit, modelID string) (bool, error) {
后续用依赖的函数替换

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
cond用$in批量拉取

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +func (a *attribute) FindObjectAttribute(kit *rest.Kit, cond mapstr.MapStr, modelBizID int64) ([]metadata.Attribute, error) {
没有bk_obj_id参数，标记为deprecated，改名为FindObjectAttributeByCondition

2021-08-02 08:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +func (a *attribute) FindBusinessAttribute(kit *rest.Kit, cond mapstr.MapStr, objID string) ([]metadata.Attribute,
这个函数当时说是改成一个通用的函数，传objID，名字改成FindObjectAttribute，然后把所有可以获取到objID的调用原本的FindObjectAttribute的地方换成用这个带objID的函数，比如FindObjectAttributeWithDetail可以换成用这个函数，它的所有调用方都可以获取到objID，所以它可以加一个objID的参数

2021-08-02 13:01 UTC, laodiu commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
源代码中没看到对IsOnly进行处理、对PropertyGroup进行了处理

2021-08-02 13:03 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
![image](https://user-images.githubusercontent.com/40779709/127866358-d4efdbb6-38b6-4349-9f6f-9408c3d815b5.png)
把每个调用的地方展开看，不要只看主体部分

2021-08-13 08:00 UTC, linfang-canway commented on src/scene_server/topo_server/logics/model/attribute.go
> +	if nil != err {
err != nil

2021-08-13 08:15 UTC, linfang-canway commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return nil, kit.CCError.New(common.CCErrTopoObjectGroupCreateFailed, err.Error())
1. 日志打印格式
2. 可以直接返回err

2021-08-13 08:16 UTC, linfang-canway commented on src/scene_server/topo_server/logics/model/attribute.go
> +		if data.IsRequired {
可以用一个if

2021-08-13 08:16 UTC, laodiu commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return nil, kit.CCError.New(common.CCErrTopoObjectGroupCreateFailed, err.Error())
这个到时候要替换掉CreateObjectGroup依赖

2021-08-20 10:30 UTC, wcy00000000000000 requested changes

2021-08-20 10:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +	attributes, err := s.Logics.AttributeOperation().FindObjectAttribute(ctx.Kit, data, common.BKInnerObjIDHost)
直接用api machinery的ReadModelAttr函数吧，data[common.BKAppIDField] = dataWithModelBizID.ModelBizID这个需要改成util.AddModelBizIDCondition(fCond, modelBizID)

2021-08-20 10:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +	data[common.BKAppIDField] = dataWithModelBizID.ModelBizID
```suggestion
	util.AddModelBizIDCondition(fCond, modelBizID)
```

2021-08-20 10:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +	resp, err := s.Logics.AttributeOperation().FindObjectAttribute(ctx.Kit, data, "")
用api machinery的ReadModelAttrByCondition吧

2021-08-20 10:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
可以直接用cond做condition一次性删掉，审计可以遍历生成存在数组里然后批量save

2021-08-20 10:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
去掉

2021-08-20 10:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	util.AddModelBizIDCondition(cond, modelBizID)
挪到下面，这里要加一个IsValid的判断

2021-08-22 08:03 UTC, laodiu commented on src/source_controller/coreservice/core/model/attribute.go
> +func (m *modelAttribute) SearchModelAttributes(kit *rest.Kit, objID string,
这个修改呢，FindObjectAttribute， FindObjectAttributeWithDetail已经使用FindBusinessAttribute改造后的通用接口替换，前面两个函数有分页，和排序功能，通过bizID作为条件查询数据，FindBusinessAttribute这个函数其实改造前和改造后都是使用objID查询数据的，且不需要分页和排序。意思改为通用接口后统一使用objID进行查询？不要再使用bizID去查询，将FindObjectAttribute，FindObjectAttributeWithDetail这两个函数的分页和排序功能都加到通用函数中？

2021-08-22 08:14 UTC, laodiu commented on src/scene_server/topo_server/logics/model/attribute.go
> +func (a *attribute) FindObjectAttribute(kit *rest.Kit, cond mapstr.MapStr, objID string) ([]metadata.Attribute, error) {
这个函数不是改造成通用函数吗？去掉？

2021-08-31 08:34 UTC, wcy00000000000000 requested changes

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	if err := a.IsValid(kit, false, data); nil != err {
```suggestion
	if err := a.IsValid(kit, false, data); err != nil {
```

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	// check the property id repeated
注释和实际内容不符

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	}
delete不需要校验，但是update需要，是否写错位置了？然后mapstruct.Decode2Struct需要结构体有mapstructure的tag，但是metadata.Attribute是没有的

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	generateAuditParameter := auditlog.NewGenerateAuditCommonParameter(kit, metadata.AuditDelete)
在用到的地方定义

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	for _, attrItem := range attrItems.Info {
遍历之前可以判断一下len(attrItems.Info)是否为0，如果为0可以提前返回

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return kit.CCError.Error(common.CCErrCommHTTPDoRequestFailed)
```suggestion
		return err
```

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return kit.CCError.New(common.CCErrTopoObjectAttributeDeleteFailed, err.Error())
```suggestion
		return err
```

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return nil, kit.CCError.Error(common.CCErrCommHTTPDoRequestFailed)
```suggestion
		return nil, err
```

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +func (a *attribute) UpdateObjectAttributeIndex(kit *rest.Kit, objID string, data mapstr.MapStr,
这个函数可以删掉，在调用的地方直接拼条件调api machinery

2021-08-31 08:34 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +		blog.Errorf("delete object attribute failed, get host apply rule failed, listRuleOption: %+v, err: %+v, "+
不需要前面的delete object attribute failed这种描述整个函数在做什么的日志

2021-09-01 03:30 UTC, wcy00000000000000 requested changes

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +func (a *attribute) createObjectGroup(kit *rest.Kit, data *metadata.Attribute) error {
这个函数名不太符合内容，这个是先检查属性的分组是否存在，不存在的话赋值为默认分组，改一下名吧

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	if resp[0] == 0 {
可以用判断resp[0] > 0直接return减少一层嵌套

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	filters = append(filters, cond)
可以直接在这里初始化filters为一个仅有一个cond的数组，下面那个也是

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return err
这里直接返回nil就好，原逻辑是不报错的，提前返回可以少一次无用的删除

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	audit := auditlog.NewObjectAttributeAuditLog(a.clientSet.CoreService())
审计挪到校验之后

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	cond[common.BKFieldID] = attID
这里可以直接初始化cond然后加biz条件，上面不用先定义，cond:=map[string]interface{}{common.BKFieldID: attID}

2021-09-01 03:30 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	lang        language.CCLanguageIf
这个在NewAttributeOperation里还是没赋值，参考之前的core里的实现

2021-09-02 03:40 UTC, wcy00000000000000 requested changes

2021-09-02 03:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +				PropertyGroupName: item.PropertyGroupName,
item里默认是没有PropertyGroupName的，需要用group id去查一下

2021-09-02 03:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	filters = append(filters, cond)
我的意思是filters := []map[string]interface{}{cond} 这样，可以把初始化和赋值放一块

2021-09-02 03:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		blog.Errorf("failed to find the attributes by the cond(%v), err: %v, rid: %s", cond, err, kit.Rid)
这个日志和实际操作不符

2021-09-02 03:40 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		return kit.CCError.Error(common.CCErrCommHTTPDoRequestFailed)
```suggestion
		return err
```

2021-09-07 09:22 UTC, wcy00000000000000 requested changes

2021-09-07 12:37 UTC, wcy00000000000000 requested changes

2021-09-07 12:37 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/association.go
> +
这个文件不用改

2021-09-07 12:37 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +}
文件末需要空行，格式化一下

2021-09-07 12:37 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		data.PropertyGroup = common.BKDefaultField
```suggestion
			data.PropertyGroup = common.BKBizDefault
			data.PropertyGroupName = common.BKBizDefault
		} else {
			data.PropertyGroup = common.BKDefaultField
			data.PropertyGroupName = common.BKDefaultField
		}
```

2021-09-07 12:37 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +	// save audit log.
保存审计挪到操作完成后，update和delete的生成审计在操作之前

2021-09-07 12:37 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +func (s *Service) getPageParam(data mapstr.MapStr)(int, int, string,error) {
这个实现不太对，调用的地方要不就用mapstruct.Decode2Struct转成metadata.BasePage类型吧，不用自己去封装了，然后data.Exists(metadata.PageName)判断是否存在和data.Remove(metadata.PageName)的逻辑要保留

2021-09-07 14:14 UTC, wcy00000000000000 requested changes

2021-09-07 14:14 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/object_attribute.go
> +	"configcenter/src/common/mapstruct"
顺序

2021-09-07 14:14 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/model/attribute.go
> +		}
刚刚搞错了，这个要放到外面，可以这样写
```
			return nil
		}
	}

	data.PropertyGroup = common.BKDefaultField
	data.PropertyGroupName = common.BKDefaultField
```

2021-09-08 06:51 UTC, breezelxp requested changes

2021-09-08 06:51 UTC, breezelxp commented on src/scene_server/topo_server/logics/model/attribute.go
> +		blog.Errorf("obj id is not valid, obj id: %+v, rid: %d.", data.ObjectID, kit.Rid)
这个是校验模型是不是存在，所以日志应该是object id is not exist, obj id: %s, rid: %s.

2021-09-08 06:51 UTC, breezelxp commented on src/scene_server/topo_server/service/object_attribute.go
> +			blog.Errorf("page info convert to struct failed, page: %v, err: %v, rid: %v", page, err, ctx.Kit.Rid)
```suggestion
			blog.Errorf("page info convert to struct failed, page: %v, err: %v, rid: %s", page, err, ctx.Kit.Rid)
```

2021-09-08 06:51 UTC, breezelxp commented on src/scene_server/topo_server/service/object_attribute.go
> +			blog.Errorf("page info convert to struct failed, page: %v, err: %v, rid: %v", page, err, ctx.Kit.Rid)
```suggestion
			blog.Errorf("page info convert to struct failed, page: %v, err: %v, rid: %s", page, err, ctx.Kit.Rid)
```

2021-09-08 07:49 UTC, breezelxp approved these changes

2021-09-08 07:49 UTC, merged