feature 优化toposerver中inst/set相关结构与代码逻辑
Tencent/bk-cmdb pull request #5556
Opened 2021-08-05 02:51 UTC by laodiu

### 优化的功能:
- 优化toposerver中inst/set相关结构与代码逻辑

issue #5450

2021-08-06 12:33 UTC, wcy00000000000000 requested changes

2021-08-06 12:33 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +	if setTemplate.ID == 0 {
用common.SetTemplateIDNotSet

2021-08-06 12:33 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +	}
去掉

2021-08-06 12:33 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +		_, err := s.CreateModule(kit, *moduleObj, bizID, int64(setID), createModuleParam)
可以改成批量加模块

2021-08-06 12:33 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +	exists, err := s.hasHost(kit, bizID, setIDs)
后续删实例接口是有判断的，这里的判断是冗余的

2021-08-06 12:33 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +}
这种不需要单独加一个FindSet接口

2021-08-09 11:44 UTC, laodiu commented on src/scene_server/topo_server/service/inst_set.go
> +	instItems, err := s.Logics.SetOperation().FindSet(ctx.Kit, obj.GetObjectID(), queryCond)
这个啥意思？没看懂

2021-09-06 03:10 UTC, wcy00000000000000 requested changes

2021-09-09 08:04 UTC, wcy00000000000000 requested changes

2021-09-09 08:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +			bizID, setTemplate.ID, err, kit.Rid)
```suggestion
		blog.Errorf("list set tpl related svc tpl failed, bizID: %d, setTemplateID: %d, err: %v, rid: %s", bizID,
			setTemplate.ID, err, kit.Rid)
```

2021-09-09 08:04 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +	setID, err := metadata.GetInstID(common.BKInnerObjIDSet, *setInstance)
*之前判断一下setInstance==nil报错返回

2021-09-09 09:19 UTC, wcy00000000000000 requested changes

2021-09-09 09:19 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_set.go
> +	if err := ctx.DecodeInto(data); err != nil {
```suggestion
	data := make(mapstr.MapStr)
	if err := ctx.DecodeInto(&data); err != nil {
```

2021-09-09 09:19 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +				"param: %#v, err: %v, rid: %s", bizID, setID, createModuleParam, err, kit.Rid)
换行位置错误，应该在bizID后换行

2021-09-09 09:19 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +	if setTemplateIDIf, ok := data[common.BKSetTemplateIDField]; ok {
可以用!ok直接return setTemplate, nil然后再查询来代替

2021-09-10 02:25 UTC, breezelxp commented on src/common/metadata/common.go
> +	BkSupplierAccount string                   `json:"bk_supplier_account"`
这个协议字段是新加的么？这里应该底层用的是header里的开发商信息。

2021-09-10 03:11 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_set.go
> +func (s *Service) createSet(kit *rest.Kit, bizID int64, data mapstr.MapStr) (*mapstr.MapStr, error) {
```suggestion
func (s *Service) createSet(kit *rest.Kit, bizID int64, data mapstr.MapStr) (mapstr.MapStr, error) {
```

map 本来就是传址的，不用加*

2021-09-10 03:23 UTC, wcy00000000000000 requested changes

2021-09-10 03:23 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/set.go
> +			return *setInstance, kit.CCError.CCError(common.CCErrorSetNameDuplicated)
直接改CreateInst的返回值为mapstr而非*mapstr，不要在外层做解引用

2021-09-10 03:23 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_set.go
> +		result := mapstr.MapStr{}
用make(mapstr.MapStr)初始化

2021-09-10 06:33 UTC, breezelxp approved these changes

2021-09-10 07:11 UTC, merged