feature 优化toposerver中inst/module相关结构与代码逻辑
Tencent/bk-cmdb pull request #5557
Opened 2021-08-05 03:24 UTC by laodiu

### 优化的功能:
- feature 优化toposerver中inst/module相关结构与代码逻辑

issue #5450

2021-08-06 09:44 UTC, wcy00000000000000 requested changes

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +func (m *module) hasHost(kit *rest.Kit, bizID int64, setIDs, moduleIDS []int64) (bool, error) {
这个在删除实例的时候有校验，这个校验重复了

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	if nil != setIDs {
用len判断，不用nil判断

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +		if err := mapstr.DecodeFromMapStr(&moduleInstance, item); err != nil {
这个没用，删了

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	UpdateModule(kit *rest.Kit, data mapstr.MapStr, obj *metadata.Object, bizID, setID, moduleID int64) error
去掉obj *metadata.Object参数

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	if count == 0 {
这个判断和下面的那个len(moduleInstances) == 0的判断可以合并

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	if err := mapstruct.Decode2Struct(moduleMapStr, &moduleInstance); err != nil {
这个可以直接在上面用ReadInstanceStruct拿到

2021-08-06 09:44 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +		}
同上

2021-09-02 07:10 UTC, wcy00000000000000 requested changes

2021-09-02 07:10 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	if err := m.clientSet.CoreService().Instance().ReadInstanceStruct(kit.Ctx, kit.Header, common.BKInnerObjIDModule,
这个用法不正确，ReadInstanceStruct读取模块时应该用new(metadata.ResponseModuleInstance)初始化

2021-09-02 07:10 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +		}
同上

2021-09-08 13:00 UTC, wcy00000000000000 requested changes

2021-09-08 13:00 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +
漏了判断moduleInstance.CCError()和原本判断数量的校验

2021-09-08 16:57 UTC, wcy00000000000000 requested changes

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	}
这个不是or关系，之前的写法比较有误导性，可以直接用cond := mapstr.MapStr{
			common.BKSetIDField: setID,
			common.BKAppIDField: bizID,
		}

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	// get set model
这个不是查集群模型，是查默认集群

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +		blog.Errorf("query set failed, err: %s, rid: %s", err, kit.Rid)
err: %v，下面的也改下

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	rsp, err := m.clientSet.CoreService().Instance().ReadInstance(kit.Ctx, kit.Header, common.BKInnerObjIDSet, query)
只需要count，可以用CountInstances

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +		serviceCategoryID = defaultServiceCategory.ID
在这个函数里对serviceCategoryID的赋值在上层是无效的

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +	if err := m.clientSet.CoreService().Instance().ReadInstanceStruct(kit.Ctx, kit.Header, common.BKInnerObjIDModule,
ReadInstanceStruct这个返回值是不带对CCError的判断的，所以要自己判断一下

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_module.go
>  		return kit.CCError.CCError(common.CCErrCommHTTPDoRequestFailed)
```suggestion
		return err
```
这种return kit.CCError.CCError(common.CCErrCommHTTPDoRequestFailed)都检查一下改成直接返回err

2021-09-08 16:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_module.go
>  	if requestBody.Modules != nil {
用len判断

2021-09-09 02:57 UTC, wcy00000000000000 requested changes

2021-09-09 02:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +	topoInstRst, err := s.Core.AssociationOperation().SearchMainlineAssociationInstTopo(ctx.Kit, common.BKInnerObjIDApp,
用logics里的，不要用core里的，就是用左边的，超长的话就换一下行

2021-09-09 02:57 UTC, wcy00000000000000 commented on src/scene_server/topo_server/logics/inst/module.go
> +			blog.Errorf("get service template not found, filter: %s, rid: %s", option, kit.Rid)
```suggestion
			blog.Errorf("get service template not found, filter: %#v, rid: %s", option, kit.Rid)
```

2021-09-09 03:07 UTC, breezelxp requested changes

2021-09-09 03:07 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/module.go
> +		if err != nil {
打个日志

2021-09-09 03:07 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/module.go
> +		if err != nil {
打个日志

2021-09-09 03:07 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/module.go
> +		return nil, kit.CCError.Errorf(common.CCErrCommParamsInvalid, "service_template_id can not be 0")
打个日志

2021-09-09 03:07 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/module.go
> +		}
打个日志

2021-09-09 03:07 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/module.go
> +			blog.V(3).Info("service category and module belong to two business, categoryBizID: %d, bizID: %d, "+
这应该是个error日志

2021-09-09 03:07 UTC, breezelxp commented on src/scene_server/topo_server/logics/inst/module.go
> +	}
补打日志

2021-09-09 07:41 UTC, breezelxp approved these changes

2021-09-09 07:41 UTC, merged