主机数据导出，将自定义topo，set，module单独放一列
Tencent/bk-cmdb pull request #5570
Opened 2021-08-11 08:22 UTC by laodiu

### 优化的功能:
- 主机导出时，默认将业务、自定义层级、集群、模块各放一列导出， 方便用户对这3个模型进行筛选

2021-09-10 09:55 UTC, wcy00000000000000 requested changes

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +			blog.ErrorJSON("BuildHostExcelFromData failed, hostData: %s, err: %s, rid: %s", hostData, err.Error(),
这种带函数名之类的注释要处理下

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +func (lgc *Logics) handleExtField(extField ExtField, customLen int, objName []string,
for循环objName直接生成即可，key可以用cc_ext_前缀+objName这种格式

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +		lgc.handleCustomField(result, rowMap, extField, param.CustomLen)
赋值自定义层级等字段的逻辑挪到上面那个if ok 判断里，直接解析topos的对应位置拿到对应的topo，不需要查DB，去掉这两个函数

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +func (lgc *Logics) handleCustomField(result *metadata.TopoPathResult, rowMap mapstr.MapStr, extField ExtField,
去掉这个函数

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +func (lgc *Logics) getTopoMainlineInstRoot(ctx context.Context, header http.Header, modelBizID int64,
去掉这个函数

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +	isMainline := false
不用判断，这个查出来的都是mainline的

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +	for objectID := common.BKInnerObjIDApp; len(objectID) != 0; objectID = mainlineObjectChildMap[objectID] {
直接在这个循环里判断非IsInnerModel才放进objectIDs

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +		Fields: []string{common.BKObjNameField, common.BKAsstObjIDField},
```suggestion
		Fields: []string{common.BKObjNameField, common.BKObjIDField},
```

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +		for _, val := range objects.Data.Info {
不要两层for循环，遍历objects.Data.Info生成一个objIDNameMap，然后直接匹配

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel.go
> +	customLen = int(mainlineAsstRsp.Data.Count) - 3
customLen即len(objName)，没必要返回

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/util.go
> +	excelColIndex++
原本的这段是为了拿到最后一列的index，ext放最前面的话就不需要了

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/fields.go
> +		//column
这段注释这么写有问题，可以这样
```suggestion
		// ExcelColIndex=tip + biztopo + biz + set + moudle + customLen, the former indexes is used by these columns
		ExcelColIndex: index,
```

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/fields.go
> +// ExtField 处理主机数据导出自定义层级字段
去掉

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel_util.go
> +	//字典中的值为国际化之后的"业务拓扑"和"业务名"，用来做判断，命中即变化相应的cell颜色。
集群、模块等也要加到注释里

2021-09-10 09:55 UTC, wcy00000000000000 commented on src/web_server/logics/excel_util.go
> +	}
直接for循环objName赋值即可

2021-09-17 14:10 UTC, wcy00000000000000 requested changes

2021-09-17 14:10 UTC, wcy00000000000000 commented on src/web_server/service/host.go
> +	}
去掉

2021-09-17 14:10 UTC, wcy00000000000000 commented on src/web_server/service/host.go
> +	for objectID := common.BKInnerObjIDApp; len(objectID) != 0; objectID = mainlineObjectChildMap[objectID] {
这里直接过滤掉业务/集群/模块，可以用判断是否为inner object的方式过滤，下面的过滤就可以去掉了

2021-09-17 14:10 UTC, wcy00000000000000 commented on src/web_server/service/host.go
> +	input := &metadata.QueryCondition{
查之前判断一下自定义层级objectIDs是否长度为0

2021-09-17 14:10 UTC, wcy00000000000000 commented on src/web_server/service/host.go
> +	hostCustomNameMaps := make([]map[string]map[int64]string, 0) // 主机id和自定义层级inst name map
没必要定义一个hostCustomNameMaps吧，hostCustomObjMap就可以定义主机和自定义层级的关系了

2021-09-17 14:10 UTC, wcy00000000000000 commented on src/web_server/service/host.go
> +	hostCustomObjMap := make(map[string]map[int64]string, 0)
可以改成hostID->objID->name的格式，或者去掉这些把hostInfo传进来直接赋值就可以去掉handleHostData了

2021-09-17 14:10 UTC, wcy00000000000000 commented on src/web_server/service/host.go
> +					if obj == objID {
map可以直接用obj拿到value，不需要这样遍历

2021-09-18 02:01 UTC, laodiu commented on src/web_server/logics/util.go
> +func addExtFields(fields map[string]Property, extFields map[string]string, extFieldKey []string) map[string]Property {
这个没懂意思、我这样遍历的目的是要进行排序、生成表头顺序为 业务拓扑、业务、自定义层级1 、2 、3 、。。。、集群、模块

2021-09-18 02:04 UTC, laodiu commented on src/web_server/logics/excel.go
> +		rowMap[extFieldsModuleID] = hostData["modules"]           // 添加模块列
查询hostinfo中有common.BKInnerObjIDModule这个key、不能使用了

2021-09-18 02:07 UTC, laodiu commented on src/web_server/logics/excel.go
> +			blog.Errorf("setExcelRowDataByIndex inst:%+v, not inst id key:%s, objID:%s, rid:%s", rowMap, instIDKey,
以后只要修改的函数、日志打印不规范的都修改

2021-09-18 02:16 UTC, laodiu commented on src/web_server/logics/excel_util.go
>  	bizTopoMap := map[string]int{
这函数没动过、暂时不修改吧

2021-09-18 02:46 UTC, laodiu commented on src/web_server/logics/util.go
> +func addExtFields(fields map[string]Property, extFields map[string]string, extFieldKey []string) map[string]Property {
![image](https://user-images.githubusercontent.com/39582223/133869859-d1fd5d3b-0ef0-406f-aa87-7194efefa06b.png)

2021-09-18 03:07 UTC, laodiu commented on src/web_server/service/host.go
> +	}
无需特殊处理、host数据查询时就已经过滤掉了

2021-09-18 07:38 UTC, laodiu commented on src/web_server/logics/fields.go
>  		field.ExcelColIndex = field.ExcelColIndex + 1
这里不需要调整+index，加了index是这个效果
![image](https://user-images.githubusercontent.com/39582223/133880654-01e32c07-2d72-4251-9360-a812a6141c7c.png)
没加index的效果才是正确的
![image](https://user-images.githubusercontent.com/39582223/133880686-77e9f3cd-2678-4b1a-969b-883e49f2e142.png)

2021-09-22 07:28 UTC, laodiu commented on src/web_server/logics/fields.go
>  		field.ExcelColIndex = field.ExcelColIndex + 1
这个地方保留了原来的写法field.ExcelColIndex = field.ExcelColIndex + 1

2021-09-22 07:29 UTC, laodiu commented on src/web_server/logics/util.go
> +func addExtFields(fields map[string]Property, extFields map[string]string, extFieldKey []string) map[string]Property {
这里暂时保留现有逻辑

2021-09-22 07:35 UTC, laodiu commented on src/web_server/logics/excel.go
> +		rowMap[extFieldsModuleID] = hostData["modules"]           // 添加模块列
查询主机数据时包含有module、set这样的键，不能使用common.BKInnerObjIDModule、故暂不做修改

2021-09-22 07:41 UTC, laodiu commented on src/web_server/logics/excel.go
>  	extFields := map[string]string{
这里需要对字段进行排序、而且需要用到extFields中的key值、而objName含有中文、实现上暂不考虑用objName替换extFields

2021-09-22 12:07 UTC, tiger-guo commented on src/web_server/service/host.go
> +		for moduleName, _ := range moduleNameMap {
```suggestion
		for moduleName  := range moduleNameMap {
```

2021-09-22 12:07 UTC, tiger-guo commented on src/web_server/service/host.go
> +				return nil, nil, fmt.Errorf("from host data get set name, not exist, rid: %s", rid)
这里缺少日志，以及Errof中只有 rid 信息，没有 error

2021-09-22 12:07 UTC, tiger-guo commented on src/web_server/service/host.go
> +		for setName, _ := range setNameMap {
```suggestion
		for setName := range setNameMap {
```

2021-09-22 12:07 UTC, tiger-guo commented on src/web_server/service/host.go
> +	sets, err := s.Engine.CoreAPI.CoreService().Instance().ReadInstance(ctx, header, common.BKInnerObjIDSet, querySet)
webserver 不能直接去调 coresevice 接口，需要调 apiserver的接口，一共有4个需要都改了

2021-09-22 13:42 UTC, laodiu commented on src/web_server/logics/excel_util.go
> +	for i := 3; i < 1000; i++ {
这里保持原有的1000设计

2021-09-26 09:11 UTC, breezelxp approved these changes

2021-09-26 09:11 UTC, merged