新版全文检索
Tencent/bk-cmdb pull request #5571
Opened 2021-08-12 02:52 UTC by wjyfelen

### 新加的功能:
- 重构全文检索，并优化全文检索性能#5507

2021-08-12 15:30 UTC, breezelxp requested changes

2021-08-12 15:30 UTC, breezelxp commented on src/scene_server/topo_server/service/fulltextsearch.go
> +			if inst, ok := instance.(*mapstr.MapStr); ok {
这个地方是不是应该判断!ok，然后报错返回？不然接下来数据可能都是错的，如L680行。

2021-08-12 15:30 UTC, breezelxp commented on src/scene_server/topo_server/service/fulltextsearch.go
> +		return
```suggestion
	if mainSearchResult.Hits.TotalHits.Value == 0 {
	        ctx.RespEntity(response)
		return
	} 
       
       response = FullTextSearchResp{Total: total}
```

2021-08-12 15:30 UTC, breezelxp commented on src/scene_server/topo_server/service/fulltextsearch.go
> +	mainESQuery, _ := esQuery.Source()
这里是有返回一个error么？

2021-08-12 15:30 UTC, breezelxp commented on src/scene_server/topo_server/service/fulltextsearch.go
> +func (s *Service) fullTextMetadata(ctx *rest.Contexts, hits []*elastic.SearchHit, request FullTextSearchReq) ([]SearchResult, error) {
这个函数太大了，要拆，单函数按规范要求不能超过85行

2021-08-12 15:30 UTC, breezelxp commented on src/scene_server/topo_server/service/fulltextsearch.go
> +	if enabled, _ := specialCharacters[r.QueryString]; enabled {
```suggestion
	if specialCharacters[r.QueryString] {
```

2021-08-13 06:48 UTC, wjyfelen commented on src/thirdparty/elasticsearch/esclient.go
> +		blog.Errorf("es count cond[%v] failed, err: %v, rid: %s", query, err, rid)
search的顺便也改了 把条件也放到了上层打印

2021-08-18 10:15 UTC, breezelxp commented on src/tools/monstache_plugin/plugin.go
> +	switch t.Kind() {
按这么麻烦，直接fmt.sprtintf()格式化是不是就可以了？

2021-08-18 10:15 UTC, breezelxp commented on src/tools/monstache_plugin/plugin.go
> +
多了个空行

2021-08-18 11:37 UTC, wjyfelen commented on src/scene_server/topo_server/service/fulltextsearch.go
> +	ctx.SetReadPreference(common.SecondaryPreferredMode)
这个是在525行有赋值，所以定义在了502行for循环之前

2021-08-18 11:41 UTC, wjyfelen commented on src/scene_server/topo_server/service/fulltextsearch.go
> +		// all the information to search is in "keywords",so delete the other key.
后面做高亮字段关联的，所以还是得根据不同表的metaid进行找

2021-08-18 11:43 UTC, wjyfelen commented on src/scene_server/topo_server/service/fulltextsearch.go
> +			blog.Warnf("fulltext handle search source, unknown data kind: %s, rid: %s", dataKind, ctx.Kit.Rid)
理论上这块是不可能出现第三种情况的，所以应该不会影响，我把这的日志改成error打印出来吧

2021-08-18 11:46 UTC, wjyfelen commented on src/scene_server/topo_server/service/fulltextsearch.go
> +			// we don't need highlight with meta_bk_obj_id and meta_bk_biz_id, just like <em>meta_bk_obj_id</em>, <em>meta_bk_biz_id</em>
是的，现在的方式是 如果关键字命中了bizid或者objid，那么就将<em>meta_bk_biz_id</em>变成meta_bk_biz_id 返回给前端，这块是继承上一版本的高亮处理。

2021-08-18 12:22 UTC, wjyfelen commented on src/tools/monstache_plugin/etc/config.toml
> +mapper-plugin-path = "etc/monstache-plugin.so"
这个是相对路径，相对于monstache二进制的路径

2021-09-13 09:30 UTC, merged