feature 提供新实例审计查询接口给前端资源池变更记录使用
Tencent/bk-cmdb pull request #5759
Opened 2021-11-11 07:57 UTC by chalice-1831

### 新加的功能:
- 提供新接口给资源池的变更记录功能使用，鉴权方式与操作审计不同，根据用户是否有实例查看权限进行鉴权。

issue #5758

2021-11-18 09:07 UTC, breezelxp requested changes

2021-11-18 09:07 UTC, breezelxp commented on src/ac/parser/topology.go
> +			if query.Condition.ObjID == common.BKInnerObjIDHost && query.Condition.BizID < 2 {
query.Condition.BizID < 2，这个是什么意思，非资源池？不能这么写

2021-11-18 09:07 UTC, breezelxp commented on src/ac/parser/topology.go
> +						InstanceID: query.Condition.BizID,
参数校验

2021-11-18 09:07 UTC, breezelxp commented on src/common/metadata/audit.go
> +func (input *InstAuditQueryInput) Validate() errors.RawErrorInfo {
应该做严格的校验，除了主机及通用模型外，其它都不能查

2021-11-18 09:07 UTC, breezelxp commented on src/scene_server/topo_server/service/auditlog.go
> +// 该函数仅供前端调用！
明确与另外的审计接口的区别，说明背景及原因

2021-11-18 09:07 UTC, breezelxp commented on src/scene_server/topo_server/service/auditlog.go
> +	if isMainline && query.Condition.BizID == 0 {
```suggestion
	if isMainline && query.Condition.BizID <= 0 {
```

2021-11-18 09:07 UTC, breezelxp commented on src/scene_server/topo_server/service/auditlog.go
> +	timeCond, _ := parseOperationTimeCondition(ctx.Kit, query.Condition.OperationTime)
返回参数不能忽略

2021-11-18 09:07 UTC, breezelxp commented on src/scene_server/topo_server/service/auditlog.go
> +// 该函数仅供前端调用！
你只加了一个接口，查详情的怎么处理？

2021-11-18 09:10 UTC, chalice-1831 commented on src/scene_server/topo_server/service/auditlog.go
> +// 该函数仅供前端调用！
查详情的通过with_detail这个字段进行控制输出

2021-11-18 09:11 UTC, chalice-1831 commented on src/common/metadata/audit.go
> +func (input *InstAuditQueryInput) Validate() errors.RawErrorInfo {
业务实例里也有变更记录，这个应该要放开，针对非主机、业务和通用模型的查询进行限制？

2021-11-18 09:26 UTC, chalice-1831 commented on src/ac/parser/topology.go
> +			if query.Condition.ObjID == common.BKInnerObjIDHost && query.Condition.BizID < 2 {
判断当前主机处于未分配状态的时候，主机业务是1 资源池 这里改为不等于1可以吗？

2021-11-18 09:30 UTC, breezelxp commented on src/ac/parser/topology.go
> +			if query.Condition.ObjID == common.BKInnerObjIDHost && query.Condition.BizID < 2 {
肯定不可以，这个值在不同的环境里值是不一样的，不一定都是从1开始的

2021-11-29 09:05 UTC, breezelxp requested changes

2021-11-29 09:05 UTC, breezelxp commented on src/scene_server/topo_server/service/auditlog.go
> +	case metadata.ModelInstanceRes:
default: 的怎么处理？补上对应的逻辑

2021-11-29 09:05 UTC, breezelxp commented on src/scene_server/topo_server/service/auditlog.go
> +func (s *Service) SearchInstAudit(ctx *rest.Contexts) {
这函数超长了吧

2021-12-02 09:11 UTC, breezelxp approved these changes

2021-12-02 09:11 UTC, merged