attribute校验规则添加对table类型的逻辑
Tencent/bk-cmdb pull request #5778
Opened 2021-11-25 09:34 UTC by chalice-1831

### 新加的功能:
- attribute校验规则添加对table类型的逻辑

2021-11-29 08:13 UTC, wcy00000000000000 reviewed
需要再次确认一下table类型是不是object数组还是只有bind_info特殊
如果是通用的话需要把bind_info的校验也改成用这里的validate而非特殊逻辑

2021-11-29 08:13 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
> +		if attribute.IsRequired {
```suggestion
	if val == nil && attribute.IsRequired {
```

2021-11-29 08:13 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
>  // validTable valid object attribute that is bool type
```suggestion
// validTable valid object attribute that is table type
```

2021-11-29 08:13 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
> +				continue
是否需要报错或者去掉多余的？

2021-11-29 08:13 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
> +			subAttr.Description = getString(option["description"])
这种转换逻辑是不是可以封装一个函数？

2021-12-02 09:48 UTC, breezelxp requested changes

2021-12-02 09:48 UTC, breezelxp commented on src/common/metadata/attribute.go
> +	valArr, ok := val.([]interface{})
val==nil 时需要不需要校验？

2021-12-02 11:32 UTC, chalice-1831 commented on src/common/metadata/attribute.go
> +	valArr, ok := val.([]interface{})
val == nil时上面已经返回了

2021-12-02 11:33 UTC, chalice-1831 commented on src/common/metadata/attribute.go
> +		if attribute.IsRequired {
这里有一个判断是 val==nil时如果不是必须判断的就返回了，如果改成这样 val==nil时attr不需要校验会走下面的逻辑不会返回

2021-12-02 11:35 UTC, chalice-1831 commented on src/common/metadata/attribute.go
> +				continue
这里可能会有多个属性进来，如果不是cc_ObjAttr里必须要校验的table子项，应该不需要报错或者去掉吧？直接进下一个循环直到需要校验的属性校验完即可？

2021-12-02 11:39 UTC, chalice-1831 commented
> 需要再次确认一下table类型是不是object数组还是只有bind_info特殊 如果是通用的话需要把bind_info的校验也改成用这里的validate而非特殊逻辑

这个table是在有服务模板且绑定了监听信息的时候新增服务模板实例会用到，这里会校验传进来的参数的合法性，我理解的是你说的bind_info的校验是在创建服务模板的时候的校验逻辑，那里是校验bind_info填的信息是否为限制填写的内容，这里应该保留原有的专门校验bind_info内容的逻辑会更好些？而这里的table校验是通用校验逻辑

2021-12-03 09:31 UTC, breezelxp commented on src/common/metadata/attribute.go
> +				continue
table表里不能出现不应该有的字段，如果有，要报错

2021-12-06 07:24 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
> +func parseSubAttribute(options []interface{}, subAttrs *[]SubAttribute) error {
为什么要把subAttrs作为参数传入呢？实际上传的是空的，放返回值是不是好点？

2021-12-06 07:24 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
> +		if option, ok := optionVal.(map[string]interface{}); ok {
可以用switch type判断吧

2021-12-06 07:24 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.9.202112061431/add_bind_info_option.go
> +			return fmt.Errorf("bind_info option already has field template_row_id")
应该直接返回不报错，报错的话就不可重入了

2021-12-07 03:18 UTC, breezelxp approved these changes

2021-12-07 03:18 UTC, merged