禁止default>0的内置集群模块通过接口修改
Tencent/bk-cmdb pull request #5780
Opened 2021-11-26 04:51 UTC by ZQHcode

### 优化的功能:
- 禁止default>0的内置集群模块通过接口修改

2021-11-29 03:32 UTC, wjyfelen commented on src/scene_server/topo_server/service/inst_module.go
> +		blog.ErrorJSON("decode set failed, data: %s, err: %v, rid: %s", setData, err, kit.Rid)
errorjson 需要用%s

2021-11-29 04:00 UTC, wjyfelen approved these changes

2021-11-29 04:00 UTC, wjyfelen commented on src/scene_server/topo_server/service/inst_module.go
> +		blog.Errorf("CheckIsBuiltInModule failed, err: %v, rid: %s", err, ctx.Kit.Rid)
不要把函数名打印到日志中

2021-11-29 06:20 UTC, wcy00000000000000 requested changes

2021-12-02 09:37 UTC, breezelxp requested changes

2021-12-02 09:37 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_module.go
>  			},
这个条件有问题，资源池下的模块怎么办?

2021-12-02 09:38 UTC, breezelxp requested changes

2021-12-02 09:38 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_module.go
>  			},
还有集群呢？

2021-12-02 12:13 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_module.go
> +				common.BKDBNIN: []int{common.DefaultFlagDefaultValue, common.DefaultResSelfDefinedModuleFlag},
这里是不是应该有注释？

2021-12-07 02:00 UTC, breezelxp approved these changes

2021-12-07 02:01 UTC, merged