优化服务模板同步
Tencent/bk-cmdb pull request #5785
Opened 2021-11-26 10:59 UTC by wjyfelen

### 新加的功能:
- 优化服务模板同步

2021-11-30 09:28 UTC, laodiu commented on src/scene_server/proc_server/service/serviceinstance.go
> +			err, procIDs, ctx.Kit.Rid)
不建议使用ErrorJSON，日志中也不建议直接出现函数名，err:%s少了空格err: %s，建议使用err: %v

2021-11-30 09:28 UTC, laodiu commented on src/scene_server/proc_server/service/serviceinstance.go
> +	serviceInstanceIDs := make([]int64, 0)
这里初始化切片，可以考虑给定len(sInstances)作为serviceInstanceIDs 切片的长度

2021-11-30 09:28 UTC, laodiu commented on src/scene_server/proc_server/service/serviceinstance.go
> +		blog.ErrorJSON("getRelations failed, option: %s, err: %s, rid: %s", option, err.Error(), ctx.Kit.Rid)
ErrorJSON有性能问题，建议替换成Errorf，日志可以尽量不要携带函数名，建议直接使用err（err.Error()）

2021-11-30 09:28 UTC, laodiu commented on src/scene_server/proc_server/service/serviceinstance.go
> +	if err != nil {
建议打印日志

2021-11-30 09:28 UTC, laodiu commented on src/scene_server/proc_server/service/serviceinstance.go
> +	if err != nil {
建议加上日志

2021-12-02 08:52 UTC, wcy00000000000000 requested changes

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +	diffDetails := new(metadata.ServiceInstanceDetailResult)
在用到的地方定义

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +	fileds := []string{common.BKFieldID, common.BKHostIDField}
```suggestion
	fields := []string{common.BKFieldID, common.BKHostIDField}
```

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +			continue
这里continue的话后面的遍历是没有意义的，应该直接return吧

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +		diffDetails.Type = metadata.ServiceChanged
同上

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +func listServiceCategoryInstances(count uint64, serviceInts []serviceListBrief) *metadata.ListServiceInstancesResult {
是否可以改成直接在上层就只查500个？

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +	option *metadata.ListServiceInstancesOption) (*metadata.ListServiceInstancesResult, errors.CCErrorCoder) {
```suggestion
func (ps *ProcServer) ListServiceInstances(ctx *rest.Contexts, option *metadata.ListServiceInstancesOption) (
	*metadata.ListServiceInstancesResult, errors.CCErrorCoder) {
```

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +	serviceInstances, err := ps.getServiceInstances(ctx, module, nil, field)
为什么不判断if err != nil？

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +		//relations := serviceRelationMap[serviceInstance[common.BKFieldID].(int64)]
没用的注释清掉

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +		if num > metadata.ServiceInstancesMaxNum {
是否可以改成一次查500个，不够再查？

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +	// 加入将没有实例化的主机.
```suggestion
	// 加入没有实例化的主机
```

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +			Id:   0,
0的没必要写出来

2021-12-02 08:52 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/serviceinstance.go
> +	sInsts := new(metadata.MultipleServiceInstance)
为什么不直接在下面查询的时候用:=初始化？

2021-12-02 09:14 UTC, wjyfelen commented on src/scene_server/proc_server/service/serviceinstance.go
> +		if num > metadata.ServiceInstancesMaxNum {
因为不确定需要查多少次，所以分页全量查

2021-12-07 10:28 UTC, breezelxp commented on src/scene_server/proc_server/service/serviceinstance.go
> +				flag = true
break

2021-12-07 11:56 UTC, wcy00000000000000 approved these changes

2021-12-07 11:58 UTC, merged