升级cmdb的平台管理配置
Tencent/bk-cmdb pull request #5791
Opened 2021-12-02 09:58 UTC by wjyfelen

### 新加的功能:
-升级cmdb的平台管理配置 #5782

2021-12-04 08:28 UTC, wcy00000000000000 requested changes

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	cnt, _, err := b.module.FindModule(ctx, obj, queryCond)
可以直接用count只查数量，3.10里有唯一索引可以去掉这个判断重复的逻辑

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +			return fmt.Errorf("idle name cannot be the same"), false, ""
为什么不用ctx.Kit.CCError生成错误？

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +// 1、key如果存在这个key只要名字不重复即合法
现在的校验是名字和之前不能一样，是否需要判断名字和所有当前名字不一样？

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +			} else if m.Key == input.Key && m.Value != input.Name {
可以扩在一个if m.Key == input.Key的大条件下或者去掉这个else if分支，因为前面直接return了

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +		if found {
为什么要用found倒一手？直接在上面设置flag就好了呀

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +
加个日志，删掉多的空行

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	res, err := b.clientSet.CoreService().System().SearchPlatformSetting(context.Background(), header)
校验的时候查了一次，实际操作时又查了一次，可否合并？

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +// 以上步骤成功后返回。均在一个事务中
日志不匹配吧

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +		defaultCategory, err := b.clientSet.CoreService().Process().GetDefaultServiceCategory(kit.Ctx, kit.Header)
不要在for循环里查这个同样的数据

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	queryCond := &metadata.QueryInput{
为什么要先查出来全部模块再用id更新？直接用这个condition更新就好了吧

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	queryCond := &metadata.QueryInput{
带上fields只查id（考虑下是否需要分页查

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	results, err := b.getIdleSetList(kit)
同上，为什么不直接拿condition更新？

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +func (b *business) getIdleSetList(kit *rest.Kit) (results []inst.Inst, err error) {
传个fields吧

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	count, _, err := b.set.FindSet(kit, obj, querySet)
同上，可以直接用count，3.10后用唯一索引校验，可以去掉

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	results, err := b.getIdleSetList(kit)
干掉，删模块不需要查集群

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +func (b *business) deleteModuleName(kit *rest.Kit, results []inst.Inst, op *metadata.BuiltInModuleDeleteOption) error {
results无用，干掉

2021-12-04 08:28 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	results, err := b.getIdleSetList(kit)
挪到新增的场景里，更新不需要查

2021-12-05 13:04 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	"configcenter/src/common/auditlog"
已改

2021-12-05 13:08 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	DeleteBusinessGlobalUserModule(kit *rest.Kit, obj model.Object, option *metadata.BuiltInModuleDeleteOption) error
已经补充到了函数定义上

2021-12-05 13:13 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +				updateFields.Set("user_module", option.Name)
增加key的审计，此场景对于审计来说没有新增只是对以前的更新

2021-12-05 13:17 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +			return fmt.Errorf("idle name cannot be the same"), false, ""
最上层是error

2021-12-05 13:23 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +// 1、key如果存在这个key只要名字不重复即合法
在checkModuleNameValid 这个函数中判断的是是否和当前有重复的，这个是判断"空闲池中"配置中是否有重复的 我改一下名字这样比较容易理解

2021-12-05 13:30 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +
在上层加了日志

2021-12-05 13:37 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	res, err := b.clientSet.CoreService().System().SearchPlatformSetting(context.Background(), header)
可

2021-12-05 13:38 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +// 以上步骤成功后返回。均在一个事务中
done

2021-12-05 13:38 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +		defaultCategory, err := b.clientSet.CoreService().Process().GetDefaultServiceCategory(kit.Ctx, kit.Header)
done

2021-12-05 13:41 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	results, err := b.getIdleSetList(kit)
done

2021-12-05 13:42 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +func (b *business) deleteModuleName(kit *rest.Kit, results []inst.Inst, op *metadata.BuiltInModuleDeleteOption) error {
done

2021-12-05 13:44 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	results, err := b.getIdleSetList(kit)
done

2021-12-05 13:58 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	queryCond := &metadata.QueryInput{
done

2021-12-05 14:02 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +func (b *business) getIdleSetList(kit *rest.Kit) (results []inst.Inst, err error) {
done

2021-12-05 14:02 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	results, err := b.getIdleSetList(kit)
done

2021-12-05 14:02 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	queryCond := &metadata.QueryInput{
done

2021-12-05 14:03 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +			} else if m.Key == input.Key && m.Value != input.Name {
done

2021-12-05 14:03 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +		if found {
done

2021-12-05 14:06 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	res, err := b.clientSet.CoreService().System().SearchPlatformSetting(context.Background(), header)
done

2021-12-05 14:06 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	header := util.BuildHeader(common.CCSystemOperatorUserName, common.BKDefaultOwnerID)
done

2021-12-06 03:00 UTC, wjyfelen commented on src/scene_server/topo_server/core/operation/inst_business.go
> +	cnt, _, err := b.module.FindModule(ctx, obj, queryCond)
在3.10中修改

2021-12-07 03:47 UTC, breezelxp approved these changes
LGTM

2021-12-07 11:53 UTC, wcy00000000000000 approved these changes

2021-12-07 11:55 UTC, merged