增加支持多个业务的空闲机模块中的主机转移到同一个业务的空闲机模块
Tencent/bk-cmdb pull request #5810
Opened 2021-12-12 11:10 UTC by wjyfelen

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2021-12-17 09:38 UTC, wcy00000000000000 requested changes

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +	HostConfigData, errors.CCErrorCoder) {
这里的断句可以在左括号后，这个看起来比较奇怪

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +func (lgc *Logics) transferParamValidate(kit *rest.Kit, bizIDs, hostIDs []int64, dstAppID, moduleID int64,
bizIDs这个参数不应该包含dstAppID吧，下面查模块的时候直接在参数用append了dst的数组就好，然后也不需要srcBizIDMap，如果dst是源业务中的一部分的话就直接全部append进去，否则直接判断模块的业务不是dstAppID就好

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +		blog.Errorf("the returned information generated error, err: %v, rid: %s", err, kit.Rid)
对不上

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +		blog.Errorf("get hosts in modules failed, err: %v, appID: %d, hostID: %d, rid: %s", err, srcBizIDs, hostIDs,
```suggestion
		blog.Errorf("check hosts in biz failed, err: %v, bizIDs: %v, hostIDs: %v, rid: %s", err, srcBizIDs, hostIDs, 
```

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +			common.BKDefaultField: map[string]interface{}{common.BKDBNE: common.NormalModuleFlag},
确认一下是要空闲机还是所有空闲模块

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/ac/parser/host.go
> +					Action: meta.MoveHostToAnotherBizModule,
这里的权限确认一下如果目标业务是主机池的话怎么办？是否允许这种情况？因为这种情况下是主机归还主机池权限

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +	err := lgc.transferParamValidate(kit, bizIDs, hostIDs, dstAppID, moduleID, srcBizIDMap)
这里直接把全部主机传进去判断，万一主机和业务的对应关系不正确怎么办？

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +	if len(hostIDs) > common.BKMaxInstanceLimit {
是否需要判断transResources、主机ID和模块id的长度不为空？

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/host/transfer/transfer.go
> +	if len(t.srcBizIDs) > 1 || (len(t.srcBizIDs) == 1 && t.srcBizIDs[0] != 0) {
判断len>0就行，没有src的话不传

2021-12-17 09:38 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/module.go
> +	if err := ctx.DecodeInto(&data); nil != err {
上面是指针了，不用再取地址了，然后err != nil

2021-12-20 15:56 UTC, breezelxp commented on src/ac/parser/host.go
> +		for _, bizId := range bizIds {
加个校验，len(bizIDs) != 0

2021-12-20 15:56 UTC, breezelxp commented on src/common/util/model.go
> +	"fmt"
?

2021-12-20 15:56 UTC, breezelxp commented on src/common/util/model.go
> +		}
```suggestion
		if bizId <= 0 {
			return fmt.Errorf("biz id illegal biz id: %d", bizId)

		} else  {
			bizIds = append(bizIds, bizId)
		}
```

2021-12-20 15:56 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +func (lgc *Logics) bizParamsIfDefaultAppName(kit *rest.Kit, allBizIDs []int64) errors.CCError {
hasResourcePoolBizExist(kit *rest.Kit, allBizIDs []int64)(bool, error)

2021-12-20 15:56 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +	if err := lgc.bizParamsIfDefaultAppName(kit, allBizIDs); err != nil {
提出来，只校验一次

2021-12-20 15:56 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +// delete old business host and module relation.
注释优化下，支持的场景就是多对一的，“支持将多个业务下的空闲机模块下的主机一次转移到另外一个业务下的空闲机set下的任一模块。”

2021-12-20 15:56 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +	//err = lgc.transferParamValidate(kit, srcBizIDs, hostIDs, dstAppID, moduleID)
delete

2021-12-20 15:56 UTC, breezelxp commented on src/scene_server/host_server/service/module.go
> +			blog.Errorf("transfer host across business failed, err: %v, input: %v, rid: %s", err, data, ctx.Kit.Rid)
```suggestion
			blog.Errorf("transfer host across business failed, input: %v, err: %v, rid: %s", data, err, ctx.Kit.Rid)
```

2021-12-20 15:56 UTC, breezelxp commented on src/source_controller/coreservice/core/host/transfer/transfer.go
> +	relationCond := map[string]interface{}{
加个注释，说明关系数据可能不准确。

2021-12-20 15:56 UTC, breezelxp commented on src/source_controller/coreservice/service/instances_dependence.go
> +		if err := util.AddModelBizIDsCondition(bizCond, bizIDs); err != nil {
AddModelWithMultipleBizIDCondition

2021-12-21 12:05 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +// transResourcesValidateHostRelations 1、判断所有主机是否在空闲机下面。2、判断是否有主机与业务对应关系是否合法。
```suggestion
// transResourcesValidateHostRelations 1、判断所有主机是否在空闲机下面。2、判断主机与业务对应关系是否一致。
```

2021-12-21 12:05 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +// transResourcesValidateModuleParams 判断所传的目的moduleID 是否合法.
```suggestion
// transResourcesValidateDstModuleParams 判断所传的目的moduleID 是否合法.
```

2021-12-21 12:05 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +// TransferResourceHostsAcrossBusiness  支持多个业务的空闲机池下空闲机转移到另外一个业务的空闲机池下的任意模块.
```suggestion
// TransferResourceHostsAcrossBusiness  支持多个业务下的空闲机模块下的主机转移到另外一个业务的空闲机池下的任意模块.
```

2021-12-21 12:12 UTC, breezelxp approved these changes

2021-12-21 12:58 UTC, merged