feature 添加接口用于查询实例关联关系以及实例详情
Tencent/bk-cmdb pull request #5861
Opened 2021-12-23 09:38 UTC by chalice-1831

### 新加的功能:
- 添加接口用于查询实例关联关系以及实例详情

close  #5807

2021-12-27 09:14 UTC, wcy00000000000000 requested changes

2021-12-27 09:14 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +				resp.ErrMsg["src"] = err
直接报错返回，不要resp.ErrMsg，下同

2021-12-27 09:14 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +	if !metadata.IsCommon(objID) && objID != common.BKInnerObjIDHost {
确认这段逻辑，之前业务、主线等也可以建关联

2021-12-27 09:14 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/association.go
> +	err := s.AuthManager.AuthorizeByInstanceID(ctx.Kit.Ctx, ctx.Kit.Header, meta.FindMany, objID, insts...)
这个函数包含了所有实例的鉴权（包括主机），没必要上面单独写

2022-01-13 03:17 UTC, breezelxp approved these changes

2022-01-13 03:18 UTC, breezelxp approved these changes

2022-01-13 03:18 UTC, merged