业务集创建查询upgrader等功能
Tencent/bk-cmdb pull request #5883
Opened 2021-12-30 08:16 UTC by wjyfelen

2021-12-30 14:12 UTC, wcy00000000000000 requested changes

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +func (s *Service) getBizSetIDList(ctx *rest.Contexts, bizSetIDs []int64) ([]int64, error) {
用kit不要用ctx

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +	bizSetIDs []int64, blag bool) (*metadata.CommonSearchResult, error) {
是否是flag？

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +	// 这个标记标明用户是否需要返回field
是否是标记是否返回业务集id？

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +	// BizSetPropertyFilter
？

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +	if searchCond.BizSetPropertyFilter != nil {
为什么这个为nil的时候不校验？

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +		searchCond.Fields = []string{common.BKBizSetIDField}
直接count之后返回，不需要设置这两个，也不要传到后面

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +		ctx.RespErrorCodeOnly(common.CCErrCommParamsInvalid, "")
为什么不返回err？加一条日志吧

2021-12-30 14:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +		return
去掉这段enable count相关的逻辑

2021-12-31 04:00 UTC, wjyfelen commented on src/scene_server/topo_server/service/inst_business_set.go
> +	bizSetIDs []int64, blag bool) (*metadata.CommonSearchResult, error) {
需要处理一下是否返回biz_setid

2022-01-04 07:09 UTC, wcy00000000000000 requested changes

2022-01-04 07:09 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +				ctx.RespEntity(0)
RespEntity之后要return

2022-01-04 07:09 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +	}
count的情况用CountObjectInstances而非SearchObjectInstances

2022-01-05 10:08 UTC, wcy00000000000000 approved these changes

2022-01-05 12:14 UTC, breezelxp approved these changes

2022-01-05 12:14 UTC, merged