feature 查询主机及其对应topo增加自定义层级查询条件
Tencent/bk-cmdb pull request #5893
Opened 2022-01-04 08:13 UTC by chalice-1831

### 优化的功能:
- 查询主机及其对应topo增加自定义层级查询条件
close #5891

2022-02-08 08:12 UTC, wjyfelen approved these changes

2022-02-08 08:12 UTC, wjyfelen commented on src/common/metadata/hostserver.go
> +		if key, err := filter.Validate(); err != nil {
1、这里是否需要补充判断元素个数和rule的数量？
	op := &querybuilder.RuleOption{
		NeedSameSliceElementType: true,
		MaxSliceElementsCount:    querybuilder.DefaultMaxSliceElementsCount,
		MaxConditionOrRulesCount: querybuilder.DefaultMaxConditionOrRulesCount,
	}

2022-02-08 08:12 UTC, wjyfelen commented on src/scene_server/host_server/logics/instance.go
> +func (lgc *Logics) GetInstIDsByCond(kit *rest.Kit, objID string, cond mapstr.MapStr) ([]int64, error) {
注释不正确

2022-02-08 08:12 UTC, wjyfelen commented on src/scene_server/host_server/logics/instance.go
> +func (lgc *Logics) GetInstIDNameInfo(kit *rest.Kit, objID string, cond mapstr.MapStr) (map[int64]string, error) {
GetInstIDNameInfo 这个函数貌似没有调用，确认一下

2022-02-08 08:27 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +func (lgc *Logics) GetObjInstParentID(kit *rest.Kit, objID string, instID int64) (int64, errors.CCErrorCoder) {
注释描述与函数返回结果不一致

2022-02-08 08:27 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +func (lgc *Logics) GetObjInstParentID(kit *rest.Kit, objID string, instID int64) (int64, errors.CCErrorCoder) {
另，该函数没有调用的地方

2022-02-08 08:27 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +func (lgc *Logics) GetInstIDsByCond(kit *rest.Kit, objID string, cond mapstr.MapStr) ([]int64, error) {
非导出函数，首字母小写

2022-02-08 08:56 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +	filterIDs[common.BKInnerObjIDApp] = []int64{bizID}
filterIDs 无用变量，删除

2022-02-08 08:56 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +			blog.Errorf("custom[%s] filter %s is invalid, key: %s, err: %s, rid: %s", objID, filter, key, err, kit.Rid)
filter %+v

2022-02-08 08:56 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +	// if set filter or module filter is set, search them first to get ids to filter hosts
删除该行注释

2022-02-08 08:56 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +	objChildMap map[string]string) (map[string][]int64, error) {
函数名太长，建议精简，如getMainlineFilters

2022-02-08 08:56 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +			return nil, nil
len(filterMainlineIDs)为0时，是否应return err？

2022-02-08 09:04 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +			for _, item := range rsp {
3级for循环嵌套，圈复杂度大，须抽出函数

2022-02-08 09:04 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +	return lgc.findHostTopo(kit, hostRelation, childMap, parentMap, hostInfo, filterIDs)
按照规范不建议return函数，建议添加临时变量接收findHostTopo的返回值，再return

2022-02-08 09:30 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +	parentMap map[string]string, hostInfo map[int64]map[string]interface{}, filterIDs map[string][]int64) (
filterIDs 无用入参，须删除

2022-02-08 09:30 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +			for _, instance := range instanceRsp {
3级for循环嵌套，圈复杂度大，须抽出函数

2022-02-08 09:30 UTC, ponyhuang commented on src/scene_server/host_server/logics/instance.go
> +			instanceRsp, err := lgc.SearchInstance(kit, objectID, filter)
2级for循环中调SearchInstance，性能低下，是否可能优化？感觉mainline instance的查询，无需嵌套到hostRelation的for循环中。

2022-02-08 09:33 UTC, wjyfelen submitted a review, later dismissed

2022-02-08 09:33 UTC, wjyfelen commented on src/scene_server/host_server/logics/instance.go
> +					if defaultValue, err = util.GetIntByInterface(defaultFieldValue); err != nil {
需要确认下这里如果defaultFieldValue, exist := item[common.BKDefaultField]; !exist 直接跳过还是需要报错？

2022-02-16 03:55 UTC, chalice-1831 commented on src/common/metadata/hostserver.go
> +		if key, err := filter.Validate(); err != nil {
3.9没有&querybuilder.RuleOption{
NeedSameSliceElementType: true,
MaxSliceElementsCount: querybuilder.DefaultMaxSliceElementsCount,
MaxConditionOrRulesCount: querybuilder.DefaultMaxConditionOrRulesCount,
}这个结构体

2022-02-28 06:41 UTC, wcy00000000000000 requested changes

2022-02-28 06:41 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +	}
为什么不直接参考ListHostDetailAndTopology用ListHosts+ArrangeHostDetailAndTopology处理呢？

2022-02-28 06:41 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +func (lgc *Logics) buildFilterIDs(kit *rest.Kit, params metadata.FindHostTotalTopo) (map[string][]int64, bool, error) {
建议这个函数直接把主线模型的ID列表转成setIDs和moduleIDs，因为查主机的时候只能通过这两个查

可以从MainlinePropertyFilter的第一层开始，先查出来ID列表，然后作为parentID条件合并进下一层的filter往下查，直到最后到达set或者module

2022-02-28 06:41 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +	}
查主机的条件缺了filterIDs里和主线相关的部分

2022-02-28 06:41 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
> +				instIDs = util.IntArrIntersection(instIDs, filterIDs[objID])
这里把不在主线条件里的inst都去掉了，用户查到的主机的拓扑是不全的

2022-02-28 12:29 UTC, chalice-1831 commented on src/common/metadata/hostserver.go
> +	Fields                 []string                  `json:"fields"`
在查询逻辑里会添加一个bk_host_id在其中

2022-02-28 12:29 UTC, chalice-1831 commented on src/scene_server/host_server/logics/host.go
> +				instIDs = util.IntArrIntersection(instIDs, filterIDs[objID])
修改后这里的filterID包含所有的主线的id了 拓扑是全的

2022-03-30 03:29 UTC, breezelxp commented on src/scene_server/host_server/logics/host.go
> +			return nil, true, err
```suggestion
			return nil, false, err
```

2022-04-27 06:39 UTC, closed without merging