主机属性自动应用支持模版配置
Tencent/bk-cmdb pull request #6038
Opened 2022-03-28 02:29 UTC by ZQHcode

### 新加的功能:
- 主机属性自动应用支持模版配置 close #6037

2022-03-30 04:34 UTC, ZQHcode commented on src/common/querybuilder/types.go
> +func (r CombinedRule) GetField() []string {
拿到rule的FIeld，这里用到的场景是拿到attributeID，然后找到对应属性的主机自动应用规则，用于后续判断模块或模版是否有配置对应属性的规则

2022-04-02 06:42 UTC, wcy00000000000000 requested changes

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +func getFinalRule(rules []metadata.HostApplyRule, option *metadata.HostApplyServiceTemplateOption) []metadata.
option类型改成HostApplyPlanBase，没有用到ID

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +			if rule, exsit := keyToRule[key]; exsit {
```suggestion
			if rule, exist := keyToRule[key]; exist {
```

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +	mouleRules, err := s.CoreAPI.CoreService().HostApplyRule().ListHostApplyRule(kit.Ctx, kit.Header, bizID, ruleOption)
```suggestion
	moduleRules, err := s.CoreAPI.CoreService().HostApplyRule().ListHostApplyRule(kit.Ctx, kit.Header, bizID, ruleOption)
```

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +	templteResult, err := s.CoreAPI.CoreService().Process().ListServiceTemplates(kit.Ctx, kit.Header, &option)
```suggestion
	templateResult, err := s.CoreAPI.CoreService().Process().ListServiceTemplates(kit.Ctx, kit.Header, &option)
```

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +		if util.InArray(rule.ID, option.RemoveRuleIDs) || util.InArray(rule.ID, option.IgnoreRuleIDs) {
如果rule存在且在AdditionalRules里且在RemoveRuleIDs，这种有讨论过怎么处理吗？

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +		blog.Errorf("list host apply rule failed, option: %s, err: %v, rid: %s", option, err, ctx.Kit.Rid)
```suggestion
		blog.Errorf("list host apply rule failed, option: %+v, err: %v, rid: %s", option, err, ctx.Kit.Rid)
```

2022-04-02 06:42 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/hostapplyrule.go
> +	if err := checkIDs([]int64{planRequest.ID}); err != nil {
就一个ID直接判断不为0就可以了，下同

2022-04-02 07:10 UTC, ZQHcode commented on src/source_controller/coreservice/core/hostapplyrule/plan.go
> +		count++
count记录的是应用到的主机数

2022-04-02 08:52 UTC, ZQHcode commented on src/source_controller/coreservice/core/hostapplyrule/rule.go
> +	moduleToRules, moduleIDs := getRuleRelationIDs(rules, module)
是没有影响的

2022-04-02 09:19 UTC, ZQHcode commented on src/source_controller/coreservice/core/hostapplyrule/rule.go
> +	for index, val := range fields {
因为传过来的是attributeID，咱结构体里的是string，这里传进来需要转成int64对应attributeID

2022-04-02 09:53 UTC, ZQHcode commented on src/scene_server/host_server/service/hostapplyrule.go
> +		if util.InArray(rule.ID, option.RemoveRuleIDs) || util.InArray(rule.ID, option.IgnoreRuleIDs) {
这里和以前逻辑一样把RemoveRuleIDs放后面的，所以会忽略的

2022-04-27 06:59 UTC, merged