添加BlueKing全业务的业务集
Tencent/bk-cmdb pull request #6082
Opened 2022-04-19 06:15 UTC by ZQHcode

### 新加的功能:
- 添加BlueKing全业务的业务集

2022-04-19 06:31 UTC, wcy00000000000000 commented on src/common/metadata/toposerver.go
> +	Filter   *querybuilder.QueryFilter `json:"filter" bson:"filter,omitempty"`
json是否也要加？

2022-04-19 06:31 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/add_business_set.go
> +	if len(result) == 1 {
确认一下这里的逻辑是要报错还是更新

2022-04-19 06:41 UTC, wjyfelen commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/add_business_set.go
> +		blog.Errorf("business set id %s or name %s already exists, the number of business set that meet the "+
这个不是“or”的关系，应该是查出来两个不同的了

2022-04-19 06:41 UTC, wjyfelen commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/add_business_set.go
> +		if result[0].BizSetID == bizSetID && result[0].BizSetName == bizSetName && result[0].Scope.MatchAll {
1、这里可能得确认下是否还需要比较creator、BizSetMaintainer和ownerID？
2、result[0].Scope.MatchAll  这么直接取是否可能会panic？
3、从数据库直接获取的数字是否需要转化后再比较？

2022-04-19 07:10 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/add_business_set.go
> +		if result[0].BizSetID == bizSetID && result[0].BizSetName == bizSetName && result[0].Scope.MatchAll {
1、这个可能其他job会调用接口把这几个值给改了，所以我们这不能报错
2、Scope是个结构体，所以不会报错
3、这个实际测过没有问题

2022-04-19 07:20 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/add_business_set.go
> +	if len(result) == 1 {
这个得报错，因为如果存在表示真的需要这条数据，如果更新的话是直接影响到用户数据所以需要报错

2022-04-20 08:32 UTC, wcy00000000000000 requested changes

2022-04-20 08:32 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst_business_set.go
> +		Condition:      mapstr.MapStr{common.BKBizSetIDField: mapstr.MapStr{common.BKDBIN: bizSetIDs}},
加一个default条件，直接count看有没有

2022-04-21 01:15 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/add_business_set.go
> +		common.BKDBOR: []map[string]interface{}{
这里不应该是OR，应该是AND

2022-04-21 01:15 UTC, breezelxp commented on src/scene_server/admin_server/upgrader/y3.10.202204181447/pkg.go
> +	blog.Infof("start execute y3.10.202204181447")
```suggestion
	blog.Infof("start execute y3.10.202204181447， add default business set")
```

2022-04-21 01:15 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_business_set.go
> +	if isBuiltIn && opt.Data.Scope != nil && !opt.Data.Scope.MatchAll {
这个判断条件是不是有问题？

2022-04-21 01:15 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_business_set.go
> +	if isBuiltIn && opt.Data.Scope != nil && !opt.Data.Scope.MatchAll {
这些特殊的判断条件要加注释，可以写个issue解释，在这里把issue链接贴上。

2022-04-21 01:15 UTC, breezelxp commented on src/scene_server/topo_server/service/inst_business_set.go
> +	}
和update的抽成一个公共的函数，然后注释说明为什么要这么做。

2022-04-21 06:16 UTC, breezelxp approved these changes

2022-04-21 06:16 UTC, breezelxp approved these changes

2022-04-21 06:16 UTC, merged