添加新增主机到业务空闲机接口
Tencent/bk-cmdb pull request #6169
Opened 2022-06-01 08:08 UTC by ZQHcode

### 新加的功能:
- 添加新增主机到业务空闲机接口

2022-06-02 07:22 UTC, wcy00000000000000 commented
缺权限相关的逻辑

2022-06-02 08:30 UTC, wcy00000000000000 requested changes

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/host.go
> +	}
业务访问权限的话直接在parser里加，去掉这个

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/host.go
> +	cond.Set(common.BKDefaultField, common.DefaultResModuleFlag)
直接用mapstr生成条件吧

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/host.go
> +	moduleID, _, err := s.Logic.GetResourcePoolModuleID(ctx.Kit, cond)
这个函数的所有调用方都没有用到name这个返回值，看看要不要去掉

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/service/host.go
> +		ctx.RespAutoError(err)
```suggestion
		ctx.RespAutoError(txnErr)
```

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/import.go
> +		result, err := lgc.CoreAPI.CoreService().Instance().CreateInstance(kit.Ctx, kit.Header, common.BKInnerObjIDHost,
可以换成CreateManyInstance一次性新增全部主机，最好不要在for循环里这样调

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/import.go
> +			blog.Errorf("create host instance failed, input:%v, err:%v, rid:%s", input, err, kit.Rid)
日志空格注意一下，下面的也是

2022-06-02 08:30 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/import.go
> +	if len(logContents) > 0 {
这个一定会大于0吧，因为hostInfos长度一定大于0

2022-06-06 04:19 UTC, wcy00000000000000 approved these changes

2022-06-06 08:13 UTC, wjyfelen commented on src/ac/parser/host.go
> +	addHostsToBusinessPattern             = "/api/v3/hosts/add/business"
接口名字是否可以改成语义更加明确的添加到业务空闲机池类似于"/api/v3/hosts/add/business_idle"

2022-06-06 11:47 UTC, wjyfelen approved these changes

2022-06-06 11:47 UTC, wcy00000000000000 approved these changes

2022-06-06 11:47 UTC, merged