修复es中存储的string无法转换为int
Tencent/bk-cmdb pull request #6189
Opened 2022-06-10 04:23 UTC by laodiu

### 修复的问题：
- 修复es中将mongo的int字段存为string类型，从es中查询结果，无法将string转为int

2022-06-10 12:58 UTC, wcy00000000000000 requested changes

2022-06-10 12:58 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/fulltextsearch.go
> +func getInt64ByInterface(a interface{}) (int64, error) {
不要加个包括全部int类型+string的方法，都知道是string了就直接用strconv转就行

2022-06-11 01:42 UTC, laodiu commented on src/scene_server/topo_server/service/fulltextsearch.go
> +func getInt64ByInterface(a interface{}) (int64, error) {
不同的es版本，不一定都是存的string，所以要兼容int和string

2022-06-13 06:21 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/fulltextsearch.go
> +func getInt64ByInterface(a interface{}) (int64, error) {
这个字段在存的时候就是用的string，这里读出来也应该是string

2022-06-13 06:30 UTC, laodiu commented on src/scene_server/topo_server/service/fulltextsearch.go
> +func getInt64ByInterface(a interface{}) (int64, error) {
metaID, err := strconv.ParseInt(source[metadata.IndexPropertyID].(string), 10, 64)

2022-06-13 11:51 UTC, wjyfelen submitted a review, later dismissed

2022-06-13 14:10 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/fulltextsearch.go
> +		metaID, err := strconv.ParseInt(source[metadata.IndexPropertyID].(string), 10, 64)
.(string)可能会Panic，可以用util.GetStrByInterface

2022-06-14 03:18 UTC, ZQHcode approved these changes

2022-06-14 03:26 UTC, wcy00000000000000 approved these changes

2022-06-14 03:26 UTC, merged