新增集群模版配置字段接口
Tencent/bk-cmdb pull request #6192
Opened 2022-06-13 05:29 UTC by ZQHcode

### 新加的功能:
- 新增集群模版配置字段接口

2022-06-14 12:37 UTC, wcy00000000000000 requested changes

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/ac/parser/servicetemplate.go
> +		ResourceAction: meta.Delete,
应该是update吧

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/ac/parser/settemplate.go
> +		ResourceAction: meta.Delete,
同上

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/ac/parser/servicetemplate.go
> +		Name:           "updateServiceTemplateAttribute",
服务模板的权限是实例级的，这个是不是要精确到服务模板实例？
集群模板也是

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/settemplate/set_template_attr.go
> +	filter := map[string]interface{}{
是否需要排除掉集群名称字段？

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/settemplate/set_template_attr.go
> +		blog.Errorf("get module attribute failed, filter: %+v, err: %v, rid: %s", filter, err, kit.Rid)
```suggestion
		blog.Errorf("get set attribute failed, filter: %+v, err: %v, rid: %s", filter, err, kit.Rid)
```

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/settemplate/set_template_attr.go
> +	attrIDs []int64) errors.CCErrorCoder {
是否需要加一个attrIDs的len>0的校验？

2022-06-14 12:37 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/settemplate/set_template_attr.go
> +			blog.Errorf("update set template attribute failed, filter: %s, err: %v, rid: %s", attrFilter, err,
```suggestion
			blog.Errorf("update set template attribute failed, filter: %v, err: %v, rid: %s", attrFilter, err,
```

2022-06-15 03:22 UTC, ZQHcode commented on src/source_controller/coreservice/core/settemplate/set_template_attr.go
> +	filter := map[string]interface{}{
因为创建那里不可能有集群名称字段等，所以这里也不用吧

2022-06-15 03:22 UTC, ZQHcode commented on src/source_controller/coreservice/core/settemplate/set_template_attr.go
> +	attrIDs []int64) errors.CCErrorCoder {
这个每个操作前都会有校验，所以这里面就不用加了吧

2022-06-15 03:59 UTC, wcy00000000000000 approved these changes

2022-06-15 03:59 UTC, merged