删除集群/模块属性时同时删除集群/服务模板的配置字段
Tencent/bk-cmdb pull request #6207
Opened 2022-06-16 13:23 UTC by ZQHcode

### 优化的功能:
- 删除集群/模块属性时同时删除集群/服务模板的配置字段

2022-06-16 13:35 UTC, wcy00000000000000 requested changes

2022-06-16 13:35 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/model/attribute.go
> +			err)
这个日志格式有问题

2022-06-17 02:19 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/model/attribute_curd.go
> +		}
不要在for循环里一个个删，用in批量删

2022-06-17 08:31 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/model/attribute_curd.go
> +		blog.ErrorJSON("delete object attributes with cond: %s, but delete these attribute in instance failed, "+
ErrorJSON只能用%s，这里有个%v，这里可以直接用Errorf

2022-06-17 08:31 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/model/attribute_curd.go
> +		blog.Errorf("delete the relation between attributes and templates failed, attr: %s, err: %v, rid: %s",
attr不应该用%s

2022-06-20 02:29 UTC, wjyfelen commented on src/source_controller/coreservice/core/model/attribute_curd.go
> +		cond := mapstr.MapStr{
cond := mapstr.MapStr{这里可以放到循环外进行定义初始化，直接赋值util.SetQueryOwner ，循环中就不用每次定义了

2022-06-22 03:07 UTC, wjyfelen submitted a review, later dismissed

2022-06-24 02:26 UTC, breezelxp commented on src/source_controller/coreservice/core/model/attribute_curd.go
> +	if err := m.cleanAttrTemplateRelation(kit.Ctx, kit.SupplierAccount, resultAttrs); err != nil {
加注释

2022-06-24 02:26 UTC, breezelxp commented on src/source_controller/coreservice/core/model/attribute_curd.go
> +			common.BKAttributeIDField: mapstr.MapStr{common.BKDBIN: attrIDs},
如果len(attrIDs) ==0 后边逻辑是不是都不用跑了，你现在这个写法，每次一定要多执行一次

2022-06-24 03:36 UTC, breezelxp approved these changes

2022-06-24 03:36 UTC, merged