修复无法查看未分配主机的变更记录详情
Tencent/bk-cmdb pull request #6270
Opened 2022-07-28 03:21 UTC by laodiu

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- 修复无法查看未分配主机的变更记录详情

2022-07-28 03:47 UTC, wcy00000000000000 requested changes
不要这样改主线判断逻辑，要改的话就改彻底一点，把obj.IsMainlineObject()和association那里的IsMainlineObject函数的逻辑都改了，不然就对不上了

2022-08-02 07:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/model/object.go
> +	IsMainlineObject(kit *rest.Kit, objID string) (bool, error)
不需要加这两个参数，object里面内置有这两个参数

2022-08-02 07:55 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst.go
> +	// forbidden create mainline instance with common api
这块逻辑为什么要改？

2022-08-03 12:09 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst.go
> -	// forbidden create mainline instance with common api
为什么要去掉校验？

2022-08-03 12:09 UTC, wcy00000000000000 commented on src/scene_server/topo_server/core/operation/inst.go
> -	isMainline, err := obj.IsMainlineObject()
这段为什么要改？

2022-08-03 12:11 UTC, laodiu commented on src/scene_server/topo_server/service/inst.go
> -	// forbidden create mainline instance with common api
这不是在后面的函数里会校验吗？

2022-08-03 12:12 UTC, wcy00000000000000 commented on src/scene_server/topo_server/service/inst.go
> -	// forbidden create mainline instance with common api
最好不要动这段逻辑，只调整一下主线的判断逻辑即可

2022-09-06 13:50 UTC, wjyfelen approved these changes

2022-09-07 03:33 UTC, wcy00000000000000 approved these changes

2022-09-07 03:33 UTC, merged