将空闲机池下的主机转移至资源池
Tencent/bk-cmdb pull request #6289
Opened 2022-08-08 03:17 UTC by wjyfelen

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2022-08-08 08:09 UTC, wcy00000000000000 requested changes

2022-08-08 08:09 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/module.go
> +				Field: common.BKDefaultField, Operator: common.BKDBNE, Value: common.NormalModuleFlag,
appid的条件带上

2022-08-08 09:54 UTC, ZQHcode commented on src/scene_server/host_server/logics/module.go
> +		blog.Errorf("move host to resource pool, module not found, cond: %+v, param: %+v, rid: %s", conf, cond, kit.Rid)
日志里的cond位置不对，233行也是

2022-08-08 11:33 UTC, wjyfelen commented on src/scene_server/host_server/logics/module.go
> +		blog.Errorf("move host to resource pool, module not found, cond: %+v, param: %+v, rid: %s", conf, cond, kit.Rid)
这个是日志中的cond是用户的参数。param是获取模块的参数所以是正确的，我把239的cond改成input的吧，比较好理解

2022-08-10 03:24 UTC, wcy00000000000000 approved these changes

2022-08-10 03:41 UTC, ZQHcode approved these changes

2022-09-02 09:43 UTC, merged