容器化表结构的upgrader
Tencent/bk-cmdb pull request #6292
Opened 2022-08-08 08:50 UTC by wjyfelen

### 新加的功能:
- 容器化数据纳管各个表的初始化以及表索引建立

2022-08-08 12:32 UTC, wjyfelen commented on src/scene_server/admin_server/upgrader/y3.10.202207251408/init_container_collection.go
> +		if _, exist := existIdxMap[index.Name]; exist {
不能去掉，因为如果索引都存在就不用create了

2022-08-10 07:33 UTC, wcy00000000000000 requested changes

2022-08-10 07:33 UTC, wcy00000000000000 commented on src/common/index/collections/container.go
> +		Unique:     true,
所有唯一索引的默认生成逻辑里都有表示类型的partial filter，看一下这里的这些是否需要补充

2022-08-10 07:33 UTC, wcy00000000000000 commented on src/scene_server/admin_server/imports.go
> +	_ "configcenter/src/scene_server/admin_server/upgrader/y3.10.202207251408"
调到今天

2022-08-10 07:33 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.10.202207251408/init_container_collection.go
> +func addPodTableIndexes(ctx context.Context, db dal.RDB) error {
可以抽成公共函数，传入表名和indexes

2022-08-10 07:33 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.10.202207251408/init_container_collection.go
> +	if len(existIdxMap) != 0 && (len(existIdxMap) < len(podIndexes)) {
upgrader应该只新增索引，这里不应该校验长度，因为用户或后续我们新增的索引可能造成这里数量不一致

2022-09-15 12:40 UTC, closed without merging