容器数据表结构字段描述
Tencent/bk-cmdb pull request #6293
Opened 2022-08-08 12:06 UTC by wjyfelen

### 新加的功能:
- 容器数据表结构字段描述

2022-08-10 03:21 UTC, wcy00000000000000 requested changes

2022-08-10 03:21 UTC, wcy00000000000000 commented on src/kube/types/types.go
> +// Revision resource version information.
```suggestion
// Revision resource revision information.
```

2022-08-10 03:21 UTC, wcy00000000000000 commented on src/kube/types/types.go
> +// IsCreateEmpty insert data case validator and creator.
注释调整下，后面的几个函数注释都是对不上的

2022-08-10 03:21 UTC, wcy00000000000000 commented on src/kube/types/types.go
> +const lagSeconds = 5 * 60
看一下是否需要允许用户配置

2022-08-10 03:21 UTC, wcy00000000000000 commented on src/kube/types/types.go
> +func (r Revision) IsCreateEmpty() bool {
这个函数什么情况下会用到？一般情况下应该都是用ValidateCreate吧

2022-08-10 03:21 UTC, wcy00000000000000 commented on src/kube/types/types.go
> +	if len(r.Creator) != 0 {
这个是否需要确认下是否值一样？防止传多了
然后为什么不校验CreateTime是否更新呢？

2022-08-10 03:21 UTC, wcy00000000000000 commented on src/kube/types/types.go
> +	{Field: NetworkTypeField, Type: Enum, Required: false, IsEditable: true, Option: map[string]string{}},
这个option为什么是空的呢？

2022-08-11 11:20 UTC, wjyfelen commented on src/kube/types/types.go
> +	BKIDField = "id"
如果不重新定义可能会导致循环嵌套，所以考虑重新定义

2022-08-11 11:34 UTC, wjyfelen commented on src/kube/types/types.go
> +	fieldType map[string]FieldType
一个是获取所有的fields，一个是方便获取每个字段类型

2022-08-11 12:10 UTC, wjyfelen commented on src/kube/types/types.go
> +	{Field: NetworkTypeField, Type: Enum, Required: false, IsEditable: true, Option: map[string]string{}},
再别的pr才设定了 这个里面么有这个 我删掉

2022-09-15 12:40 UTC, closed without merging