调整权限初始化操作
Tencent/bk-cmdb pull request #6344
Opened 2022-09-13 03:19 UTC by wjyfelen

2022-09-13 04:08 UTC, ZQHcode approved these changes

2022-09-13 11:55 UTC, wcy00000000000000 requested changes

2022-09-13 11:55 UTC, wcy00000000000000 commented on src/ac/iam/initial_common_actions.go
> +			EnglishName: "Business Maintainer",
下面的action缺了业务查看权限，再检查一下还有没有别的要调整的吧

2022-09-14 06:57 UTC, wcy00000000000000 approved these changes

2022-09-14 06:58 UTC, merged