并发获取用户数据时，出现并发读写map导致webserver服务panic
Tencent/bk-cmdb pull request #6413
Opened 2022-10-12 07:20 UTC by laodiu

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- 在请求用户数据时，传递的参数param为map类型，会出现并发读写导致panic
![企业微信截图_16655579407012](https://user-images.githubusercontent.com/39582223/195275099-eda9eba9-1579-479f-8371-d76bfcf91849.png)

2022-10-12 07:50 UTC, wcy00000000000000 requested changes

2022-10-12 07:50 UTC, wcy00000000000000 commented on src/thirdparty/esbserver/user/api.go
> +	var lock sync.RWMutex
这个锁在这个函数里定义是没有用的

2022-10-12 07:52 UTC, laodiu commented on src/thirdparty/esbserver/user/api.go
> +	var lock sync.RWMutex
这个函数里不用加锁是吧，那去掉了

2022-10-12 08:00 UTC, wcy00000000000000 commented on src/thirdparty/esbserver/user/api.go
> +	var lock sync.RWMutex
我的意思是你这个锁不是共享的，没有用
然后这里不需要加锁处理，把params深拷贝一下即可

2022-10-12 08:01 UTC, laodiu commented on src/thirdparty/esbserver/user/api.go
> +	var lock sync.RWMutex
OK

2022-10-23 11:31 UTC, wjyfelen commented on src/web_server/service/util.go
这种直接断言的写法感觉有点奇怪,其实也可以把params当成参数传到闭包中

2022-10-24 02:46 UTC, wcy00000000000000 commented on src/web_server/service/util.go
> -			userListEsbSub, errNew := user.GetUserList(c, params)
把103-104的内容挪到126前面就可以解决这个并发问题了

2022-10-24 02:51 UTC, laodiu commented on src/web_server/service/util.go
按Kelsey的方案进行调整了

2022-10-25 13:41 UTC, wjyfelen approved these changes

2022-10-25 13:41 UTC, wcy00000000000000 approved these changes

2022-10-25 13:42 UTC, merged