支持主机ipv6单栈相关调整
Tencent/bk-cmdb pull request #6528
Opened 2022-12-08 09:06 UTC by ZQHcode

### 新加的功能:
- 添加校验内网ipv4地址是否必填的的hook

### 优化的功能:
- 优化服务模版同步时，当没有ipv4时使用ipv6作为服务实例名称前缀
- 优化同步索引时将“0”改为“static”
- 更新主机云区域时，如果为静态寻址方式则判断内网ipv4+云区域或内网ipv6地址+云区域是否重复
- 去除部分判断ipv4字段必须获取到的校验逻辑
- 调整主机权限资源名称

### 修复的问题：
- 修复更新主机云区域接口不报错的问题
- 修复转移主机到模块接口不报错问题
- 修复添加主机时没判断云区域是否存在的问题

2022-12-12 13:29 UTC, wjyfelen commented on src/source_controller/coreservice/core/process/base.go
> +	return util.GetStrByInterface(host[common.BKHostInnerIPField]), nil
这里得确认下，如果类型不对的话是否需要放过。还是需要报错

2022-12-12 13:29 UTC, wjyfelen commented on src/thirdparty/hooks/host.go
> +/*
之前有一个validate的文件，是否可以将这个函数放到validate文件中

2022-12-12 13:29 UTC, wjyfelen commented on src/scene_server/admin_server/upgrader/y3.10.202211220949/add_agent_id_related_attr.go
> +				common.BKAddressingField:  common.BKAddressingStatic,
这里最好是写成"static",因为如果后续宏变了，不会影响这个upgrader的数据

2022-12-12 13:29 UTC, wjyfelen commented on src/scene_server/host_server/logics/plat.go
> +func (lgc *Logics) IsPlatExist(kit *rest.Kit, cloudIDs []int64) (bool, errors.CCError) {
这个函数的名字最好改一下因为部分存在也代表不存在，改成类似于IsPlatAllExist这种语义清晰些

2022-12-12 14:22 UTC, ZQHcode commented on src/source_controller/cacheservice/cache/host/host.go
> +	ips := util.GetStrByInterface(host[common.BKHostInnerIPField])
这个在UnmarshalBSON如果有这个字段会保证是字符串类型，之前更多是怕它为空的校验，所以这里需要做的是直接拿到ips去进行赋值

2022-12-13 09:13 UTC, wcy00000000000000 requested changes

2022-12-13 09:13 UTC, wcy00000000000000 commented on src/scene_server/host_server/logics/host.go
>  	return hostInfo, ip, nil
ip这个返回值如果上层没有用到的话可以去掉

2022-12-13 09:13 UTC, wcy00000000000000 commented on src/thirdparty/hooks/validator.go
> +func ValidHostInnerIPv4Hook(kit *rest.Kit, cloudID int64, innerIPv4 string) errors.CCErrorCoder {
这里的hook需要调整为不允许外界传入cloud ID为0的机器

2022-12-13 09:13 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/cache/host/host.go
> +	ips := util.GetStrByInterface(host[common.BKHostInnerIPField])
这个还是要分情况判断一下哈

2022-12-13 12:28 UTC, ZQHcode commented on src/source_controller/cacheservice/cache/host/host.go
> +	ips := util.GetStrByInterface(host[common.BKHostInnerIPField])
这个之前会用来如果有innerip的话，就作为key来缓存主机，现在调用的地方如果是空字符串，就会跳过

2022-12-14 12:03 UTC, wjyfelen approved these changes

2022-12-14 12:08 UTC, merged